### PR TITLE
Add eclipse project files to .gitignore

### PR DESCRIPTION
**Pull request by hedayat**

### CODE REVIEW

**Comment by AmeBel** [comment]
thanks

**Comment by AmeBel** [comment]
Assuming you are using Eclipse, would you please check http://wiki.opencog.org/wikihome/index.php/Using_Eclipse_CDT and if there is anything to update would you please point it out or update it?

**Comment by hedayat** [comment]
Sure I will. :)
Thanks.

**Comment by ngeiswei** [comment]
I knew there was a wiki page about Eclipse! @hedayat if you can have your Eclipse Section in the development standard refer to it, and possibly harmonize the 2 that would be great!

**Comment by hedayat** [comment]
@AmeBel I tried, but since I use a different Eclipse/CMake workflow (I create makefiles with CMake and import the project into Eclipse as a Makefile project rather than creating Eclipse project with CMake), I cannot update the current guidelines (if needed). 

@ngeiswei OK! I will add a section about importing code style in the Eclipse page.

**Comment by AmeBel** [comment]
Ok thanks

**Pull request merged**
