### PR TITLE
(Recreate) Add a Python conceptual blending algorithm into OpenCog

### PR DESCRIPTION
**Pull request by kim135797531**
Finished making fundamental structure of the conceptual blending algorithm.

Now works with simple algorithms(randomly blend, ...) and will be improved by adding new algorithms.

It also includes some examples and unit tests.

Documentation of Conceptual Blending Config Format will helps you to understand more clearly.

As I said in mailing list, this pull request includes little heavy unit tests and works with unstable method of finding Scheme library in Python.

This request will not affect any other parts of project.

I would appreciate feedback from yours!

### CODE REVIEW

**Comment by kim135797531** [comment]
@ngeiswei, could I ask you to review my new pull request?

**Comment by ngeiswei** [comment]
Hi @kim135797531 I'm working on it.

First remark, I think you can get rid of blending_old. It's not like it's being used by anyone and it will still be in git history.

**Comment by ngeiswei** [comment]
It all looks very clean!

Unfortunately I cannot test it, I'm having issue with running the python bindings and the wiki and repo docs seems outdated... I'm about to create an issue about that, let me know if I'm just missing something.

**Comment by ngeiswei** [comment]
@kim135797531 It seems the python module blending is not installed after compiling and installing opencog. Please fix that so I can test your code. Thanks.

FYI, if you push more commits on that branch before merging it will get included as well.

**Comment by kim135797531** [comment]
Thanks for reviewing my code. I had remove the blending_old folder, fixed typo(thanks!) and now I'm changing my config system to use ExecutionLink from ListLink.

About installing blending module, python modules don't have to compile and install. Only need to install things are python binding libraries(to /usr/local/share/opencog/python). I made a new virtual machine today to test this, and it worked normally with official install construction **except the value of PYTHONPATH.**

In [opencog/python/README.md](https://github.com/opencog/opencog/tree/master/opencog/python/README.md):
```bash
PYTHONPATH="$PYTHONPATH:$HOME/opencog/opencog/python:$HOME/opencog/build/opencog/cython"
```
but it would be changed to this:
```bash
PYTHONPATH="$PYTHONPATH:$HOME/opencog/opencog/python:/usr/local/share/opencog/python"
```
because python programs needs python binding libraries made by atomspace repo and opencog repo both, and it can be found in /usr/local/share/opencog/python together. This README.md had to be updated when split the atomspace, but it hadn't...

**Comment by ngeiswei** [comment]
Hi @kim135797531 Maybe that library should be installed. But anyway, I got an error while running example 2

```python
>>> >>> result = ConceptualBlending(a).run(
    focus_atoms,
    ConceptNode("my-config")
)

... ... ... Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/nilg/OpenCog/opencog-kim/opencog/python/blending/blend.py", line 116, in run
    get_chooser(self.config_base).\
  File "/home/nilg/OpenCog/opencog-kim/opencog/python/blending/src/chooser/chooser_finder.py", line 36, in get_chooser
    BlendConfig().get_str(self.a, "atoms-chooser", config_base)
  File "/home/nilg/OpenCog/opencog-kim/opencog/python/blending/util/blending_config.py", line 186, in get_str
    ret = cls.get(a, config_name, config_base)
  File "/home/nilg/OpenCog/opencog-kim/opencog/python/blending/util/blending_config.py", line 155, in get
    exist_set = cls.__execute_wrap("GET", config_dict)
  File "/home/nilg/OpenCog/opencog-kim/opencog/python/blending/util/blending_config.py", line 103, in __execute_wrap
    link_dict = cls.execute_link_factory.create(call_type, config_dict)
  File "/home/nilg/OpenCog/opencog-kim/opencog/python/blending/util/blending_config.py", line 367, in create
    return self.__create_get_link(config_dict)
  File "/home/nilg/OpenCog/opencog-kim/opencog/python/blending/util/blending_config.py", line 292, in __create_get_link
    free_var
  File "atomspace_details.pyx", line 116, in opencog.atomspace.AtomSpace.add_link (/home/nilg/OpenCog/atomspace/build/opencog/cython/opencog/atomspace.cpp:5547)
RuntimeError: AtomTable - Atom in outgoing set isn't known! (/home/nilg/OpenCog/atomspace/opencog/atomspace/AtomTable.cc:515)
```
could you double check, does it work for you?

**Comment by kim135797531** [comment]
Hi @ngeiswei,

Yes, I checked that example just now, it works for me. Could you tell me the output if you write the code `print free_var` in blending_config.py at 286? I can't reproduce your error..

And I'll add my module to be installed. As you mentioned in Slack, currently making environment to execute python modules is annoying work. After I finish this project I want to improve the overall structure of python binding..

**Comment by ngeiswei** [comment]
Weird, I've retried and it works. Anyway, good then, I'm coming back with more feedback...

**Comment by ngeiswei** [comment]
The code is good enough for merging. Thanks!

**Comment by ngeiswei** [comment]
Of course you can still take into my minor remarks in the subsequent merges.

**Comment by kim135797531** [comment]
@ngeiswei

I agree that InheritanceLink is more suitable for this example.

This example was designed to show how to blending algorithm works, so it doesn't make much sense to real life. Since the 'Similarity' is significant thing in conceptual blending theory I tried to make an example with SimilarityLink, that's all. I'll add more good examples after making the advanced algorithms. 

So ```MemberLink(car, metal)``` is just dummy link to show how algorithm process the non-duplicated links. In current config, blender just copy it to new node. I'll add this desctipion in next commit.

Now I'm modifying another algorithm to make it works. (Information Interaction algorithm in opencog/learning/statistics/) After finish this work, I'll return to this project.

And finally, I would like to thank you for your careful review of my work!

**Comment by bgoertzel** [comment]
>
> Now I'm modifying another algorithm to make it works. (Information
> Interaction algorithm in opencog/learning/statistics/) After finish this
> work, I'll return to this project.
>

That should be quite interesting...

**Comment by linas** [comment]
The assert /atomspace/opencog/atomspace/AtomTable.cc:515 is probably due to the fact that the python bindings are using the atom UUID's instead of the atom pointers, and is somehow deleting the atoms.  Its a design flaw in the python bindings.

**Pull request merged**
