### PR TITLE
Add Jenkins job config file

### PR DESCRIPTION
**Pull request by wenwei-dev**
This is the job config file that is currently used in Jenkins CI.

### CODE REVIEW

**Comment by AmeBel** [comment]
best if all the config files are kept @ https://github.com/opencog/docker

**Comment by AmeBel** [comment]
Does jenkins requires the config to be in root of the repo?

**Comment by wenwei-dev** [comment]
No it doesn't. Any place is okay to keep the config files.

**Comment by AmeBel** [comment]
buildbot config are kept in the docker repo, so I think it would be appropriate to have it there. As the jenkins setup is likely to be dockerized when/if we choose to deploy it on a cloud server.

**Comment by wenwei-dev** [comment]
I see. So I'll close the PRs that I've created just now and pull them to https://github.com/opencog/docker/jenkins.

**Comment by AmeBel** [comment]
great thanks

**Comment by wenwei-dev** [comment]
The config files will go to github.com/opencog/docker/jenkins.

**Pull request closed without merging**
