### PR TITLE
A  fix to issue 1147

### PR DESCRIPTION
**Pull request by misgeatgit**
The fix applied here used to exisit before commit
36d9c895353f71e9e50b9ad6ebae9e1c2f8eda9e
Unfortunately this commit will resurrect the problem solved by the
above commit.

### CODE REVIEW

**Comment by cosmoharrigan** [comment]
See comment https://github.com/opencog/opencog/issues/1147#issuecomment-68608410

**Comment by cosmoharrigan** [comment]
@misgeatgit It's great that you have identified the use of multiprocessing as being involved here. But, as you alluded to above, I don't think reverting to this prior usage of threading is a good solution, because using threading instead of multiprocessing causes other very unpleasant issues. Instead I think it would be preferable to use the knowledge you have discovered, to try to figure out how to access the shared atomspace, while using multiprocessing.

**Comment by linas** [comment]
Cosmo:  What are the threading issues?  I believe that it is fundamentally impossible to share the atomspace via shared memory.  It is making use of a large and sophisticated infrastructure inside of glibc that supports stack unwinding, local storage, stack variables, signal handling. You are not going to be able to replicate that without becoming a glibc expert, and copying large parts of that code. (I'm expounding on this, because, in one if my previous jobs, I added support for a new CPU to glibc. There is a huge wealth of complex machinery in there, that most people are quite oblivious to.  That machinery works with threads. It doe not work at all with IPC)  

Think of it this way: just think of what it would take to create a shared mem allocator!  You'd have to reproduce all of malloc!  The pool management, the COW pages, the linux kernel system calls.  And debug all of that. People have tried this in the past, and you should be able to find some package somewhere, even on github, that does this, but it will be shaky and buggy.  IPC is hard.

In addition, the atomspace also uses boost reference counting for pointers, and so you will have to figure out how to share that state across processes as well. This stuff is deep in the bowels of boost.  So you'd have to reverse-engineer boost, and figure out how to do that across IPC.   

So that's just for C+. But you are using python...   I don't think even the most serious python maintainers would know how to do that. Just read the comments in the stack-exchange articles quoted in the original bug report to get a flavor f it.

Finally: go look at the history of threading: it was invented to solve these serious and fundamental IPC issues.   Threading is just IPC without the bugs of IPC.  That's the whole point of threading. To try to go back to IPC, and try to wrestle with these deep and fundamental comp-sci issues is  ... this is not the project to do this.

**Comment by bgoertzel** [comment]
Well if the issue is just respect of the CogServer "shutdown" command,
there must be some way to solve that consistent with use of threading

Or perhaps there is a miscommunication here and Cosmo means something
different by "multiprocessing" than Linas thinks he does?

ben

On Mon, Jan 5, 2015 at 8:13 AM, Linas Vepštas <notifications@github.com>
wrote:

> Cosmo: What are the threading issues? I believe that it is fundamentally
> impossible to share the atomspace via shared memory. It is making use of a
> large and sophisticated infrastructure inside of glibc that supports stack
> unwinding, local storage, stack variables, signal handling. You are not
> going to be able to replicate that without becoming a glibc expert, and
> copying large parts of that code. (I'm expounding on this, because, in one
> if my previous jobs, I added support for a new CPU to glibc. There is a
> huge wealth of complex machinery in there, that most people are quite
> oblivious to. That machinery works with threads. It doe not work at all
> with IPC)
>
> Think of it this way: just think of what it would take to create a shared
> mem allocator! You'd have to reproduce all of malloc! The pool management,
> the COW pages, the linux kernel system calls. And debug all of that. People
> have tried this in the past, and you should be able to find some package
> somewhere, even on github, that does this, but it will be shaky and buggy.
> IPC is hard.
>
> In addition, the atomspace also uses boost reference counting for
> pointers, and so you will have to figure out how to share that state across
> processes as well. This stuff is deep in the bowels of boost. So you'd have
> to reverse-engineer boost, and figure out how to do that across IPC.
>
> So that's just for C+. But you are using python... I don't think even the
> most serious python maintainers would know how to do that. Just read the
> comments in the stack-exchange articles quoted in the original bug report
> to get a flavor f it.
>
> Finally: go look at the history of threading: it was invented to solve
> these serious and fundamental IPC issues. Threading is just IPC without the
> bugs of IPC. That's the whole point of threading. To try to go back to IPC,
> and try to wrestle with these deep and fundamental comp-sci issues is ...
> this is not the project to do this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/pull/1176#issuecomment-68656279>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by cosmoharrigan** [comment]
By "multiprocessing" I am referring to https://docs.python.org/2/library/multiprocessing.html.

> What are the threading issues?

The issue was that the thread would not exit when the cogserver exited; as a result, it would still be running in the background, and if one tried to restart the cogserver in the same shell window, one would receive an error unless the process was manually terminated. This became a particularly important issue when using the [python-client](https://github.com/opencog/python-client) external library to run experiments that required repeatedly starting and stopping the cogserver.

@misgeatgit Maybe you can try making the REST API thread into a daemon thread?
http://stackoverflow.com/questions/190010/daemon-threads-explanation

@linas Alright. I'll merge this in the meantime.

**Pull request merged**
