### PR TITLE
Fixed Ros dependency

### PR DESCRIPTION
**Pull request by rTreutlein**
I had to merge my master into this, that is why there are so many commits.

### CODE REVIEW

**Comment by pennachin** [comment]
There should be a way to cherry pick commits or something like that, I hope we don't have to merge 509 commits.

**Comment by rTreutlein** [comment]
@pennachin Well most of those are in master already so it shouldn't be to big an issue. I tried cherry-picking but there was other stuff that was failing in this branch.

**Comment by linas** [comment]
Gah, Well, I had taken a lot of time and effort to cherry-pick exactly the right stuff but Cassio revered all of it.

**Comment by linas** [comment]
Basically, you got this mess because (a) cassio reverted, and (b) he he did it wrong and then (c) you commited this without review  and (d) you did it wrong.

I'm pissed off at the fucking going around here cassio Get fucking rid of the goddamned circle CI stuff and quit making everyone's lives miserable.

**Comment by linas** [comment]
Sorry. I'm just in a bad mood, I guess.

**Pull request merged**
