### PR TITLE
Port ure pln config json to atomese

### PR DESCRIPTION
**Pull request by ngeiswei**

### CODE REVIEW

**Comment by ngeiswei** [comment]
On my way defined scheme function
```
pln-fc
pln-bc
```
to simplify fc and bc calls.

**Comment by williampma** [comment]
Hello @ngeiswei, how is the pln-config.scm loaded inside cogserver?

I tried `(load "../opencog/reasoning/pln/pln-config.scm")` and got

```
ERROR: In procedure primitive-load-path: Unable to find file "utilities.scm" in load path
```

**Comment by ngeiswei** [comment]
I've never tried to load that in the cogserver. I'll add that in my TODO list...

**Comment by linas** [comment]
`(add-to-load-path "/usr/local/share/opencog/scm")` is missing from somewhere.

**Comment by ngeiswei** [comment]
@eddiemonroe, I cannot currently run the cogserver (revision #4224bfa), I'm getting the following error:
```
nilg@laptop:~/OpenCog/opencog/scripts$ ./run_cogserver.sh 
Error: Backtrace:
In ice-9/boot-9.scm:
 157: 13 [catch #t #<catch-closure 10e7e00> ...]
In unknown file:
   ?: 12 [apply-smob/1 #<catch-closure 10e7e00>]
In ice-9/boot-9.scm:
 157: 11 [catch #t #<catch-closure 11239a0> ...]
In unknown file:
   ?: 10 [apply-smob/1 #<catch-closure 11239a0>]
   ?: 9 [call-with-input-string "(load \"..//opencog/nlp/scm/type-definitions.scm\")" ...]
In ice-9/boot-9.scm:
2320: 8 [save-module-excursion #<procedure 11e1000 at ice-9/eval-string.scm:65:9 ()>]
In ice-9/eval-string.scm:
  44: 7 [read-and-eval #<input: string ea7270> #:lang ...]
  37: 6 [lp (load "..//opencog/nlp/scm/type-definitions.scm")]
In ice-9/boot-9.scm:
2320: 5 [save-module-excursion #<procedure 1403240 at ice-9/boot-9.scm:3961:3 ()>]
3968: 4 [#<procedure 1403240 at ice-9/boot-9.scm:3961:3 ()>]
In unknown file:
   ?: 3 [load-compiled/vm "/home/nilg/.cache/guile/ccache/2.0-LE-8-2.0/home/nilg/OpenCog/opencog/opencog/nlp/scm/type-definitions.scm.go"]
In /home/nilg/OpenCog/opencog/scripts/..//opencog/nlp/scm/type-definitions.scm:
  36: 2 [#<procedure 12b8740 ()>]
In ice-9/boot-9.scm:
 102: 1 [#<procedure 1403300 at ice-9/boot-9.scm:97:6 (thrown-k . args)> unbound-variable ...]
In unknown file:
   ?: 0 [apply-smob/1 #<catch-closure 11236a0> unbound-variable ...]

ERROR: In procedure apply-smob/1:
ERROR: In procedure module-lookup: Unbound variable: DefinedLinguisticConceptNode
ABORT: unbound-variable

Listening on port 17001
```
And doing a telnet into the cogserver, I can't run anything, help returns
```
command "help" not found
```
So I'm a bit clueless, has any body the same problem?

**Comment by williampma** [comment]
It looks like the NLP atoms types are not loaded.  Are you using the default opencog.conf?

**Comment by ngeiswei** [comment]
I'm using `<OPENCOG_ROOT>/scripts/run_cogserver.sh` which loads `<OPENCOG_ROOT>/lib/opencog.conf`.

**Comment by ngeiswei** [comment]
My problem with the cogserver has magically disappeared. @williampma #1744 should fix the remaining issues to be able to load pln from the cogserver.

**Pull request merged**
