### PR TITLE
Fix for faied postgres build

### PR DESCRIPTION
**Pull request by linas**

### CODE REVIEW

**Comment by linas** [comment]
fuck jenkins ci. This is fucked up.  Ther are multiple pull requests, which fix multiple problems, but they all fail in jenkins because no one single pull request fixes all the problems at once.

The entire concept of CI is just totally fucked up and I don't understand why you guys don't fukcing understand this very simple, basic concept, and why the fuck I have to loose yet another day hacking past this abortion of an idea.   Just fucking turn the goodamned thing off and STOP MAKING ME WASTE ON TIME TRYING TO PUZZLE-SOLVE A SYSTEM THAT MAKES THE WHOLE POINT OF USING SOURCE CONTROL POINTLESS.   

WHOEVER INVENTED CICEL CI AND JENKISNS CI AND THE ENTIRE FUCKING CONCEPT SHOULD BE HANGING FROM A GODDAMNED LIGHT POLE.  THIS IS FUCKED UP.

**Comment by ngeiswei** [comment]
@linas Seriously, if multiple commits are interdependent, why don't you push them all in a specific branch and then merge that branch into the master? You could for instance have pushed to dev. You know the master is assumed not to break, you know these multiple branches need to be merged at once. You know all you need to know. WTF!

**Comment by linas** [comment]
fix the system so it works again.  quit fucking the system so that its permanently broken.  Why do I have to resort to insults and emper tantrums before anyone listens to me?

**Comment by wenwei-dev** [comment]
Oops. @linas , I'm so sorry. I just went over all the emails today, and knew just now how jenkins made you many bad days. I have created a gmail filter that marks email as highest priority if it has some keywords like "fuck" or "WTF" so next time I won't miss it.

CI is not suitable for the project that at a fast development stage I have to say. It's the case for opencog at this moment. So disable the branch protection is right.

**Pull request merged**
