### PR TITLE
Aaron's R2L work

### PR DESCRIPTION
**Pull request by linas**
cherry-pick Aaron's R2L work.

### CODE REVIEW

**Comment by williampma** [comment]
I haven't looked closely, but I am not sure you cherry-picked the right files.  @anitzkin would know perhaps.

Particularly these files
```
 opencog/reasoning/RuleEngine/rules/relex-to-logic/PREP.scm (74)
 opencog/reasoning/RuleEngine/rules/relex-to-logic/SP.scm (57)
 opencog/reasoning/RuleEngine/rules/relex-to-logic/SV.scm (57)
 opencog/reasoning/RuleEngine/rules/relex-to-logic/SVIO1.scm (92)
 opencog/reasoning/RuleEngine/rules/relex-to-logic/SVIO2.scm (92)
 opencog/reasoning/RuleEngine/rules/relex-to-logic/TOBE.scm (73)
```
shouldn't even exist as the RuleEngine path is deleted awhile back.

Surely, these files from the original PR
```
A opencog/reasoning/r2l/rules/PREP.scm (74)
A opencog/reasoning/r2l/rules/SP.scm (57)
A opencog/reasoning/r2l/rules/SV.scm (57)
A opencog/reasoning/r2l/rules/SVIO1.scm (92)
A opencog/reasoning/r2l/rules/SVIO2.scm (104)
A opencog/reasoning/r2l/rules/TOBE.scm (73)
A opencog/reasoning/r2l/rules/advmod.scm (58)
A opencog/reasoning/r2l/rules/amod.scm (62)
A opencog/reasoning/r2l/rules/attime.scm (59)
M opencog/reasoning/r2l/rules/be-inheritance.scm (2)
A opencog/reasoning/r2l/rules/because.scm (59)
A opencog/reasoning/r2l/rules/comp.scm (59)
A opencog/reasoning/r2l/rules/compmod.scm (58)
A opencog/reasoning/r2l/rules/copula-ynq.scm (76)
A opencog/reasoning/r2l/rules/how-q.scm (58)
A opencog/reasoning/r2l/rules/howdeg.scm (58)
A opencog/reasoning/r2l/rules/howpredadj1.scm (73)
A opencog/reasoning/r2l/rules/howquant.scm (58)
A opencog/reasoning/r2l/rules/imperative.scm (47)
A opencog/reasoning/r2l/rules/pp.scm (59)
A opencog/reasoning/r2l/rules/pred-ynq.scm (44)
A opencog/reasoning/r2l/rules/prepadj.scm (61)
A opencog/reasoning/r2l/rules/rep.scm (59)
M opencog/reasoning/r2l/rules/svo.scm (26)
A opencog/reasoning/r2l/rules/when-cop-q.scm (74)
A opencog/reasoning/r2l/rules/when-q.scm (61)
A opencog/reasoning/r2l/rules/where-cop-q.scm (74)
A opencog/reasoning/r2l/rules/where-q.scm (61)
A opencog/reasoning/r2l/rules/whichobjQ.scm (90)
A opencog/reasoning/r2l/rules/whichpredadjQ.scm (73)
A opencog/reasoning/r2l/rules/whichsubjQ.scm (90)
A opencog/reasoning/r2l/rules/whichsubjSVOQ.scm (90)
A opencog/reasoning/r2l/rules/why-cop-q.scm (92)
A opencog/reasoning/r2l/rules/why-q.scm (60)
```

are the correct ones?

**Comment by linas** [comment]
I did not notice that there were three copies of the files; I thought there were only two, and deleted one copy. I already deleted `opencog/reasoning/r2l/` and kept only the stuff in `nlp`

**Comment by linas** [comment]
OK, I removed the files under `opencog/reasoning/RuleEngine` with commit 0bbfad3988c6d272f006c5f0da82ca06d1bd46cd  I believe that the latest files are now in `opencog/nlp/relex2logic`

**Comment by anitzkin** [comment]
No, William, is correct; it was decided by someone (not me) that reasoning was the correct folder, and only the files in the reasoning folder (the last commit) are guaranteed working correctly . . . 

However, since I still have the correct versions of everything on my machine, there's no loss here.

**Comment by anitzkin** [comment]
The full correct path (according to whoever decided that) was reasoning/r2l/rules/ . . .

**Comment by anitzkin** [comment]
Yeah, the whole idea （in my mind) was that the one final commit had
everything correct in it, and so all the other commits could have been
discarded.

**Comment by linas** [comment]
OK, so I see that I missed one of teh commits, the last one.8b5588f39bf1eebd32f98d19c427554079412e5f  I could not actually cherry-pick that one, it had subprject garbage in it.  I just mnaully copied the files over, it is now in 2716c6b41ed0efcd53efaecff914c09ab59d9cab

**Comment by linas** [comment]
Hmm. well, next time, if you have everything in one correct commit, don't commit it on top of a bunch of wrong ones. Just create a new branch, and commit it there.  The process is
```
git checkout master
git pull
git checkout -b my-new-branch
# hack hack hack
git commit
# hack hack hack
git commit
git push
# make a pull request
git checkout master     # when starting a new task
git pull                        # get the latest version
git branch -d my-new-branch   # to delete the branch
```
Typically you would do the above every week or two.

You can't put the files under 'reasoning' that is a temporary ranch that will be deleted when Nil gets done doing whatever he is doing.   The NLP code will stay with OpenCog, it will not move to the atomspace repo.

**Comment by AmeBel** [comment]
when i wrote the prototype rules a year ago the directory was called /opencog/rule-engine/rules/r2l (or something like that) i have no preference to where it is kept now

**Comment by anitzkin** [comment]
Actually, that's excatly what I did.  If you look, you'll see that the last
commit was made on a different branch than all the others. That was my
idea.  Github still appended it to the earlier commits -- ??

**Comment by anitzkin** [comment]
Amen, somebody, I think perhaps Nil？，chimed in last week to say that they
should be in reasoning/r2l/rules.

**Pull request merged**
