### PR TITLE
Octomap feature

### PR DESCRIPTION
**Pull request by chenesan**
I have wrote the current situation of this feature in the README of:
https://github.com/chenesan/opencog/tree/OctomapFeature/opencog/spatial/3DSpaceMap

So at this time the basic functions of new spacemap are finished, but the corresponding fix in other places in opencog/ is not done. 

I know that since it will break the other code in opencog it should not be pulled at this time. But I heard from Ben that some works about robotic embodiment may start recently, and it may needs the new SpaceMap. So I think maybe it's better to post it now in the pull request and fix them gradually. I'll leave in the next week for a trip so I will return to work on them on July 28th.

### CODE REVIEW

**Comment by AmeBel** [comment]
@bgoertzel how do you want to handle this

**Comment by chenesan** [comment]
Hi @AmeBel and @bgoertzel 
For now, because I'm not sure the demands of the SpaceMap (what specific functions do who want?), so I only keep the basic add/remove/query functions in SpaceMap/SpaceMapUtil and functions I need in Minecraft embodiment. Now this breaks lots of old embodiment code since the inner logic of Octree3DMapManager changes a lot. I think that if we'll abandon old embodiment code, I'll prefer not to fix them at this time. But if it's necessary to fix the embodiment code, I can do this. But I may need 2 or 3 weeks to fix them. 
Also the document may be a little outdated, I will try to update them in the next few days.

**Comment by bgoertzel** [comment]
Cassio, perhaps we could use your advice on this...

Yi-Shan has changed some of the 3DSpacemap related code, in a way that will
work for his Minecraft application --- but his changes break some other
3dSpacemap related functionality, which will be needed for other
applications (e.g. robotics, and eventually for Minecraft too)

I will have someone in Ethiopia (probably Selameab) fix these broken
functions...

Nobody else is now using the 3dspacemap functionality anyway...

Should his new code just be merged into the master branch, or should it be
put in a separate feature branch till the other broken stuff is fixed? etc.
...

ben




On Thu, Aug 20, 2015 at 7:53 PM, Yi-Shan, Chen <notifications@github.com>
wrote:

> Hi @AmeBel <https://github.com/AmeBel> and @bgoertzel
> <https://github.com/bgoertzel>
> For now, because I'm not sure the demands of the SpaceMap (what specific
> functions do who want?), so I only keep the basic add/remove/query
> functions in SpaceMap/SpaceMapUtil and functions I need in Minecraft
> embodiment. Now this breaks lots of old embodiment code since the inner
> logic of Octree3DMapManager changes a lot. I think that if we'll abandon
> old embodiment code, I'll prefer not to fix them at this time. But if it's
> necessary to fix the embodiment code, I can do this. But I may need 2 or 3
> weeks to fix them.
> Also the document may be a little outdated, I will try to update them in
> the next few days.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/pull/1686#issuecomment-132985094>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by pennachin** [comment]
My suggestion would be to keep this in a feature branch, and merge onto
master once Yi-Shan's changes have been reconciled with existing
functionality...

On Thu, Aug 20, 2015 at 8:01 PM, bgoertzel <notifications@github.com> wrote:

> Cassio, perhaps we could use your advice on this...
>
> Yi-Shan has changed some of the 3DSpacemap related code, in a way that will
> work for his Minecraft application --- but his changes break some other
> 3dSpacemap related functionality, which will be needed for other
> applications (e.g. robotics, and eventually for Minecraft too)
>
> I will have someone in Ethiopia (probably Selameab) fix these broken
> functions...
>
> Nobody else is now using the 3dspacemap functionality anyway...
>
> Should his new code just be merged into the master branch, or should it be
> put in a separate feature branch till the other broken stuff is fixed? etc.
> ...
>
> ben
>
>
>
>
> On Thu, Aug 20, 2015 at 7:53 PM, Yi-Shan, Chen <notifications@github.com>
> wrote:
>
> > Hi @AmeBel <https://github.com/AmeBel> and @bgoertzel
> > <https://github.com/bgoertzel>
> > For now, because I'm not sure the demands of the SpaceMap (what specific
> > functions do who want?), so I only keep the basic add/remove/query
> > functions in SpaceMap/SpaceMapUtil and functions I need in Minecraft
> > embodiment. Now this breaks lots of old embodiment code since the inner
> > logic of Octree3DMapManager changes a lot. I think that if we'll abandon
> > old embodiment code, I'll prefer not to fix them at this time. But if
> it's
> > necessary to fix the embodiment code, I can do this. But I may need 2 or
> 3
> > weeks to fix them.
> > Also the document may be a little outdated, I will try to update them in
> > the next few days.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/opencog/opencog/pull/1686#issuecomment-132985094>.
> >
>
>
>
> --
> Ben Goertzel, PhD
> http://goertzel.org
>
> "The reasonable man adapts himself to the world: the unreasonable one
> persists in trying to adapt the world to himself. Therefore all progress
> depends on the unreasonable man." -- George Bernard Shaw
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/pull/1686#issuecomment-132986255>.
>



-- 
Cassio Pennachin

**Comment by bgoertzel** [comment]
So, just to be sure I understand the intended workflow ... then we'll have
basically a Minecraft feature branch, until such time as the prior
3DSpaceMap functions are all working again... and then at that time we'll
merge the 3DSpaceMap feature branch into the master branch...

In the interim, improvements to the master branch will need to be merged
ongoingly into the Minecraft feature branch (e.g. Linas's various relevant
updates to the pattern matcher and behavior trees, etc.)

So then, we just need to tell Selameab & Tesfa to do their work restoring
the prior 3DSpaceMap functions, on the Minecraft feature branch...

-- ben


On Fri, Aug 21, 2015 at 10:01 AM, Cassio Pennachin <notifications@github.com
> wrote:

> My suggestion would be to keep this in a feature branch, and merge onto
> master once Yi-Shan's changes have been reconciled with existing
> functionality...
>
> On Thu, Aug 20, 2015 at 8:01 PM, bgoertzel <notifications@github.com>
> wrote:
>
> > Cassio, perhaps we could use your advice on this...
> >
> > Yi-Shan has changed some of the 3DSpacemap related code, in a way that
> will
> > work for his Minecraft application --- but his changes break some other
> > 3dSpacemap related functionality, which will be needed for other
> > applications (e.g. robotics, and eventually for Minecraft too)
> >
> > I will have someone in Ethiopia (probably Selameab) fix these broken
> > functions...
> >
> > Nobody else is now using the 3dspacemap functionality anyway...
> >
> > Should his new code just be merged into the master branch, or should it
> be
> > put in a separate feature branch till the other broken stuff is fixed?
> etc.
> > ...
> >
> > ben
> >
> >
> >
> >
> > On Thu, Aug 20, 2015 at 7:53 PM, Yi-Shan, Chen <notifications@github.com
> >
> > wrote:
> >
> > > Hi @AmeBel <https://github.com/AmeBel> and @bgoertzel
> > > <https://github.com/bgoertzel>
> > > For now, because I'm not sure the demands of the SpaceMap (what
> specific
> > > functions do who want?), so I only keep the basic add/remove/query
> > > functions in SpaceMap/SpaceMapUtil and functions I need in Minecraft
> > > embodiment. Now this breaks lots of old embodiment code since the inner
> > > logic of Octree3DMapManager changes a lot. I think that if we'll
> abandon
> > > old embodiment code, I'll prefer not to fix them at this time. But if
> > it's
> > > necessary to fix the embodiment code, I can do this. But I may need 2
> or
> > 3
> > > weeks to fix them.
> > > Also the document may be a little outdated, I will try to update them
> in
> > > the next few days.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/opencog/opencog/pull/1686#issuecomment-132985094>.
> > >
> >
> >
> >
> > --
> > Ben Goertzel, PhD
> > http://goertzel.org
> >
> > "The reasonable man adapts himself to the world: the unreasonable one
> > persists in trying to adapt the world to himself. Therefore all progress
> > depends on the unreasonable man." -- George Bernard Shaw
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/opencog/opencog/pull/1686#issuecomment-132986255>.
> >
>
>
>
> --
> Cassio Pennachin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/pull/1686#issuecomment-133245706>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by pennachin** [comment]
Hi,

So, just to be sure I understand the intended workflow ... then we'll have
> basically a Minecraft feature branch, until such time as the prior
> 3DSpaceMap functions are all working again... and then at that time we'll
> merge the 3DSpaceMap feature branch into the master branch...
>

I'm confused, why do we need both a Minecraft feature branch and a
3DSpaceMap feature branch?


> In the interim, improvements to the master branch will need to be merged
> ongoingly into the Minecraft feature branch (e.g. Linas's various relevant
> updates to the pattern matcher and behavior trees, etc.)
>

Which is pretty simple, just on a daily basis:

git fetch
git rebase origin/master

Rebase, not merge, to preserve a clean commit history. This should be
standard practice for any feature branch, of course.

Cassio
-- 
Cassio Pennachin

**Comment by bgoertzel** [comment]
>
> I'm confused, why do we need both a Minecraft feature branch and a
> 3DSpaceMap feature branch?



OK, maybe I'm confused....  the point is the minecraft dev work depends on
the 3DSpaceMap changes....   So al the minecraft work has to occur in some
branch where Yi-Shan's 3DSpaceMap changes have been effected...

**Comment by AmeBel** [comment]
@chenesan pls modify the pull-request to point to `3DSpaceMap` branch. Thanks

**Comment by pennachin** [comment]
Hi,

OK, maybe I'm confused.... the point is the minecraft dev work depends on
> the 3DSpaceMap changes.... So al the minecraft work has to occur in some
> branch where Yi-Shan's 3DSpaceMap changes have been effected...


But why are two separate branches needed? Having feature branches branching
off of feature branches is usually a very bad idea. If the minecraft dev
work needs its own branch, then these 3DSpaceMap changes should be merged
first (i.e., the work of fixing any breakage is urgent).

Cassio
-- 
Cassio Pennachin

**Comment by AmeBel** [comment]
FYI, The minecraft side of the code is being developed in a separate repository.

**Comment by chenesan** [comment]
Hi, I have made another PR on 3DSpaceMap feature branch.
And about Minecraft embodiment I think we don't need to create another feature branch for it since we've created another repo for this.

**Comment by AmeBel** [comment]
The repo https://github.com/OC2MC/opencog-to-minecraft

**Comment by AmeBel** [comment]
Closing b/c pull request re-submitted to https://github.com/opencog/opencog/pull/1735

**Comment by pennachin** [comment]
Ok, that makes sense and the other repo should target the feature branch.

On Fri, Aug 21, 2015 at 11:47 AM, Amen Belayneh <notifications@github.com>
wrote:

> FYI, The minecraft side of the code is being developed in a separate
> repository.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/pull/1686#issuecomment-133271882>.
>



-- 
Cassio Pennachin

**Comment by ngeiswei** [comment]
Hi Cassio,

On 08/21/2015 06:06 AM, Cassio Pennachin wrote:> Which is pretty simple, 
just on a daily basis:
 >
 > git fetch
 > git rebase origin/master
 >
 > Rebase, not merge, to preserve a clean commit history. This should be
 > standard practice for any feature branch, of course.

I've come to disagree with that. They are several reasons why rebasing 
is a bad.

1. It changes the state of the commits. For instance I personally try as 
much as possible to have commits that preserve compilability (the code 
can compile). If I rebase and a previous commit breaks compiling, so 
will all my subsequent commits. That's really annoying, once you have 
that you can no longer use history bisection to find a bug.

2. If I follow someone's branch and I fetch their work their history is 
no longer coherent with the history I have locally. You can work around 
that but it's confusing. Actually when I face that, I delete my local 
folder and reclone, just out of over cautiousness. Again I'm sure there 
is a better way but still, it's confusing.

3. Git and github handle very well multiple branching/merging. If you 
make a pull request and it turns out you need to merge the last master 
branch, github won't be confused at all, it will still show **your** 
commits as the work that's been done on that branch.

So I'm not saying you should never rebase, they are situations when 
rebasing is good, and I do rebase sometimes. But I don't think rebasing 
should be the default.

Nil

**Comment by ngeiswei** [comment]
Hi Nil,

There are many long discussions on the relative merits of rebase vs merge
on the web, and no final conclusion. There are a bunch of plusses and
minuses for each option, so I'm not going to push my particular preference
around if others disagree. Just a couple of comments:

1. It changes the state of the commits. For instance I personally try as
> much as possible to have commits that preserve compilability (the code can
> compile). If I rebase and a previous commit breaks compiling, so will all
> my subsequent commits. That's really annoying, once you have that you can
> no longer use history bisection to find a bug.
>

The rebase workflow assumes you want to track master. For that to be a good
idea, one assumes master is stable, which removes this issue. One should
never rebase or merge a broken master onto a feature branch... You're right
that if it does happen, merge gives you a more useful history.


> 2. If I follow someone's branch and I fetch their work their history is no
> longer coherent with the history I have locally.


I don't understand this one. How does your fetching change someone's work
history? Rebase will change your local history only...


> 3. Git and github handle very well multiple branching/merging. If you make
> a pull request and it turns out you need to merge the last master branch,
> github won't be confused at all, it will still show **your** commits as the
> work that's been done on that branch.
>

Sure, git doesn't get confused. I (and others) do when looking through
history ;-).

Cheers,
Cassio

**Comment by ngeiswei** [comment]
On 08/21/2015 12:33 PM, Cassio Pennachin wrote:
> Hi Nil,
>
> There are many long discussions on the relative merits of rebase vs
> merge on the web, and no final conclusion. There are a bunch of plusses
> and minuses for each option, so I'm not going to push my particular
> preference around if others disagree. Just a couple of comments:
>
>     1. It changes the state of the commits. For instance I personally
>     try as much as possible to have commits that preserve compilability
>     (the code can compile). If I rebase and a previous commit breaks
>     compiling, so will all my subsequent commits. That's really
>     annoying, once you have that you can no longer use history bisection
>     to find a bug.
>
>
> The rebase workflow assumes you want to track master. For that to be a
> good idea, one assumes master is stable, which removes this issue. One
> should never rebase or merge a broken master onto a feature branch...
> You're right that if it does happen, merge gives you a more useful history.

It's probably not entirely true because someone's commit may still badly 
interact with yours, even though everything compiles well separately. 
But sure, I get your point, it might not be much of a concern in 
practice. But since I have (admittedly in rare occasions) experienced 
that problem I know it can happen.

>
>     2. If I follow someone's branch and I fetch their work their history
>     is no longer coherent with the history I have locally.
>
>
> I don't understand this one. How does your fetching change someone's
> work history? Rebase will change your local history only...

Let's say I want to follow Marcos' feature branch, I do

git clone <Marco's atomspace url> marcos-atomspace
cd marcos-atomspace
git checkout marcos-feature-branch

A few days later Marcos updates his branch, since he believes its ready 
to be merged to the master branch he decides to rebase it. I then fetch 
Marcos' repo to review his last changes

git fetch

Now we have conflicting histories.

It's not a big deal, but it is slightly confusing, it makes you waste a 
minute or so to figure out what's going on and fix it. While if Marcos 
had merged instead of rebasing, no such confusion occurs.

>
>     3. Git and github handle very well multiple branching/merging. If
>     you make a pull request and it turns out you need to merge the last
>     master branch, github won't be confused at all, it will still show
>     **your** commits as the work that's been done on that branch.
>
>
> Sure, git doesn't get confused. I (and others) do when looking through
> history ;-).

I used to think that. On the other hand it is nice to know the actual 
history as it has happened. And a good git front-end can make things 
easier, or allow to quickly check out a branch to only see it.

According to my experience, rebasing has more potential for troubles. I 
wouldn't recommend it to a git noob for instance. I guess the rule 
should be: "if you don't know what you're going then merge, otherwise do 
what you want". Of course ideally everybody should know what they're 
doing. :-)

Nil

>
> Cheers,
> Cassio
>
> --
> You received this message because you are subscribed to the Google
> Groups "opencog" group.
> To unsubscribe from this group and stop receiving emails from it, send
> an email to opencog+unsubscribe@googlegroups.com
> <mailto:opencog+unsubscribe@googlegroups.com>.
> To post to this group, send email to opencog@googlegroups.com
> <mailto:opencog@googlegroups.com>.
> Visit this group at http://groups.google.com/group/opencog.
> To view this discussion on the web visit
> https://groups.google.com/d/msgid/opencog/CADwLDSRh8%3DATrCwd9Liasj%2BozK4vpYkVy8758EmYK2r%2BFp_e%3DQ%40mail.gmail.com
> <https://groups.google.com/d/msgid/opencog/CADwLDSRh8%3DATrCwd9Liasj%2BozK4vpYkVy8758EmYK2r%2BFp_e%3DQ%40mail.gmail.com?utm_medium=email&utm_source=footer>.
> For more options, visit https://groups.google.com/d/optout.

**Comment by ngeiswei** [comment]
Hi,

It's probably not entirely true because someone's commit may still badly
> interact with yours, even though everything compiles well separately.


True, but in that situation there's no "right" history, or if there is, the
one given by rebase makes sense to me, as master runs ok.


> A few days later Marcos updates his branch, since he believes its ready to
> be merged to the master branch he decides to rebase it. I then fetch
> Marcos' repo to review his last changes
>
> git fetch
>
> Now we have conflicting histories.
>

Ah, I got it. Yes, rebase isn't good for live-tracking other people's
history.


> I used to think that. On the other hand it is nice to know the actual
> history as it has happened. And a good git front-end can make things
> easier, or allow to quickly check out a branch to only see it.
>

I haven't found the time to pursue magit enlightenment yet, I'm still using
the command line like a barbarian...


> According to my experience, rebasing has more potential for troubles. I
> wouldn't recommend it to a git noob for instance. I guess the rule should
> be: "if you don't know what you're going then merge, otherwise do what you
> want". Of course ideally everybody should know what they're doing. :-)
>

That is definitely true. Merge is much more noob friendly.

Cassio
-- 
Cassio Pennachin

**Comment by ngeiswei** [comment]
On 08/21/2015 01:19 PM, Cassio Pennachin wrote:
> Hi,
>
>     It's probably not entirely true because someone's commit may still
>     badly interact with yours, even though everything compiles well
>     separately.
>
>
> True, but in that situation there's no "right" history, or if there is,
> the one given by rebase makes sense to me, as master runs ok.

 From the perspective of the master before the feature branch, yes the 
history is right, but not from the perspective of the feature branch. 
The only true history is the parallel history, obtained by merging, and 
the only one that can be 100% reproduced. I've come to realize that this 
reproducibility is valuable, in general, not just when archiving 
experiments (you know what I mean ;). It's also safer, it doesn't break 
past references (like in Linas' diaries). Of course the good thing is 
that the one rebasing is the one rewriting **his** history, so again, as 
long as the person knows what she is doing there's mostly no problem 
with that.

Nil

>
>     A few days later Marcos updates his branch, since he believes its
>     ready to be merged to the master branch he decides to rebase it. I
>     then fetch Marcos' repo to review his last changes
>
>     git fetch
>
>     Now we have conflicting histories.
>
>
> Ah, I got it. Yes, rebase isn't good for live-tracking other people's
> history.
>
>     I used to think that. On the other hand it is nice to know the
>     actual history as it has happened. And a good git front-end can make
>     things easier, or allow to quickly check out a branch to only see it.
>
>
> I haven't found the time to pursue magit enlightenment yet, I'm still
> using the command line like a barbarian...
>
>     According to my experience, rebasing has more potential for
>     troubles. I wouldn't recommend it to a git noob for instance. I
>     guess the rule should be: "if you don't know what you're going then
>     merge, otherwise do what you want". Of course ideally everybody
>     should know what they're doing. :-)
>
>
> That is definitely true. Merge is much more noob friendly.
>
> Cassio
> --
> Cassio Pennachin
>
> --
> You received this message because you are subscribed to the Google
> Groups "opencog" group.
> To unsubscribe from this group and stop receiving emails from it, send
> an email to opencog+unsubscribe@googlegroups.com
> <mailto:opencog+unsubscribe@googlegroups.com>.
> To post to this group, send email to opencog@googlegroups.com
> <mailto:opencog@googlegroups.com>.
> Visit this group at http://groups.google.com/group/opencog.
> To view this discussion on the web visit
> https://groups.google.com/d/msgid/opencog/CADwLDSRH2hM_1cDrwgJJ2foYJtsEX0PqTWCwuvzYCkpJJnFg9A%40mail.gmail.com
> <https://groups.google.com/d/msgid/opencog/CADwLDSRH2hM_1cDrwgJJ2foYJtsEX0PqTWCwuvzYCkpJJnFg9A%40mail.gmail.com?utm_medium=email&utm_source=footer>.
> For more options, visit https://groups.google.com/d/optout.

**Comment by ngeiswei** [comment]
More advice on when to rebase and when to merge:

https://raw.githubusercontent.com/gitforteams/diagrams/master/flowcharts/rebase-or-merge.png

All the Best,

Matt

--
Please interpret brevity as me valuing your time by minimizing unnecessary
words, and not as any negative intention.

**Comment by ngeiswei** [comment]
Hi,

Yeah, given all the different issues people have pointed out, I retract my
previous recommendation and endorse Nil's:

 I guess the rule should be: "if you don't know what you're going then
> merge, otherwise do what you want". Of course ideally everybody should know
> what they're doing. :-)


Cheers,
Cassio

**Comment by ngeiswei** [comment]
Hi,

On 08/24/2015 07:52 AM, Cassio Pennachin wrote:
> Hi,
>
> Yeah, given all the different issues people have pointed out, I retract
> my previous recommendation and endorse Nil's:
>
>       I guess the rule should be: "if you don't know what you're going
>     then merge, otherwise do what you want". Of course ideally everybody
>     should know what they're doing. :-)

Oh, BTW, look at what just happened

https://github.com/opencog/atomspace/pull/230

that illustrates exactly the potential hazardousness of rebasing.

Nil

>
>
> Cheers,
> Cassio
>
> --
> You received this message because you are subscribed to the Google
> Groups "opencog" group.
> To unsubscribe from this group and stop receiving emails from it, send
> an email to opencog+unsubscribe@googlegroups.com
> <mailto:opencog+unsubscribe@googlegroups.com>.
> To post to this group, send email to opencog@googlegroups.com
> <mailto:opencog@googlegroups.com>.
> Visit this group at http://groups.google.com/group/opencog.
> To view this discussion on the web visit
> https://groups.google.com/d/msgid/opencog/CADwLDSRXYve2bKVRE8ytd0-SqLvmkVD5SxjiGgFOrChUK4kuOw%40mail.gmail.com
> <https://groups.google.com/d/msgid/opencog/CADwLDSRXYve2bKVRE8ytd0-SqLvmkVD5SxjiGgFOrChUK4kuOw%40mail.gmail.com?utm_medium=email&utm_source=footer>.
> For more options, visit https://groups.google.com/d/optout.

**Comment by ngeiswei** [comment]
On Fri, Aug 21, 2015 at 4:33 AM, Cassio Pennachin <pennachin@gmail.com> wrote:

>> 2. If I follow someone's branch and I fetch their work their history is no
>> longer coherent with the history I have locally.
>
> I don't understand this one. How does your fetching change someone's work
> history? Rebase will change your local history only...

I think Nil  is saying that pulling from multiple repositories can get
confusing.   I do this very infrequently; the solution for Nil is to
not to pull into his own master, but to pull into a branch.  Later on,
you can delete the branch, or merge it into your own master (thus
merging this other persons changes as well).

> Sure, git doesn't get confused. I (and others) do when looking through
> history ;-).

?

I've never rebased once in git; never had to, never had the urge to.
Don't know what it's good for.   Don't know why there's any confusion
about the history; its certainly much clearer than it ever was in bzr:
each branch has a distinct begining, a distinct end, and you can see
exactly what changed.

-linas

**Comment by ngeiswei** [comment]
On Fri, Aug 21, 2015 at 5:11 AM, 'Nil Geisweiller' via opencog
<opencog@googlegroups.com> wrote:

>
> Let's say I want to follow Marcos' feature branch, I do
>
> git clone <Marco's atomspace url> marcos-atomspace
> cd marcos-atomspace
> git checkout marcos-feature-branch

You are doing it wrong.  You'd do this instead:

git checkout -b my-shadow-of-marcos  # create new branch
git pull <Marco's atomspace url>  # pull hist code into new branch
fiddle, whatever.
when done:
git checkout master  # go back to your master
git pull <opencog-master>    # pull latest from opencog.
git checkout -b some-new-work   # new branch for personal work
hack hack
# time to review marcos
git checkout my-shadow-of-marcos
git pull <Marco's atomspace url>  #get the lattest code
review stuff
git checkout some-new-work
# resume hacking on personal project.

you never ever have to git clone, except once-ever.

> It's not a big deal, but it is slightly confusing, it makes you waste a
> minute or so to figure out what's going on and fix it. While if Marcos had
> merged instead of rebasing, no such confusion occurs.

Oh. Ewww.  Marcos should not be rebasing. That is a pretty strong
argument against rebasing; its fundamentally clobbering the history of
the tree.  That is so nasty-bad, it should almost be illegal...


--linas

**Comment by ngeiswei** [comment]
Another alternative:

git remote add marcos-fork <Marco's atomspace url>
git remote update
git checkout marcos-fork/master

At this point you're in detached head state, which means you can see
what things look like without creating a new branch unnecessarily. If
you want a new branch you can create one normally...

git checkout -b
whatever-you-want-to-call-your-local-branch-mirroring-marcos-master

You would also have an easy way to update and make sure you locally
have the most recent versions of the forks you care about:

git remote update -p

(-p prunes your copy of the remote branches if they are deleted at the remote)

You can then also do "git branch -av" to see all your colleagues' branches. :-)

**Comment by ngeiswei** [comment]
A friendly reminder.

When a consensus for a preferred git-workflow is 
reached, http://wiki.opencog.org/w/Development_standards#Git_HOWTO should 
be updated.

>
>

**Comment by ngeiswei** [comment]
On 08/27/2015 06:33 AM, Amen Belayneh wrote:
> A friendly reminder.
>
> When a consensus for a preferred git-workflow is
> reached, http://wiki.opencog.org/w/Development_standards#Git_HOWTO
> should be updated.

Actually it already contains it (see item 8, presumably added by Linas). 
:-) It doesn't contain Joel's checkout-without-creating-branch 
suggestion though.

Nil

>
>
> --
> You received this message because you are subscribed to the Google
> Groups "opencog" group.
> To unsubscribe from this group and stop receiving emails from it, send
> an email to opencog+unsubscribe@googlegroups.com
> <mailto:opencog+unsubscribe@googlegroups.com>.
> To post to this group, send email to opencog@googlegroups.com
> <mailto:opencog@googlegroups.com>.
> Visit this group at http://groups.google.com/group/opencog.
> To view this discussion on the web visit
> https://groups.google.com/d/msgid/opencog/4ac932d7-0c8a-44ca-847f-724afa3a5138%40googlegroups.com
> <https://groups.google.com/d/msgid/opencog/4ac932d7-0c8a-44ca-847f-724afa3a5138%40googlegroups.com?utm_medium=email&utm_source=footer>.
> For more options, visit https://groups.google.com/d/optout.

**Comment by ngeiswei** [comment]
My 2c about rebasing

I use interactive rebasing a lot (-i option) but only in this case: I'm
working on a new feature branch of my OWN fork, with branch name prefixed
with "wip-" for "work in progress", eg wip-my-totally-crazy-feature,  so
that anybody taking it does it as its own risk.
When the feature start to stabilize and I expect others to fork it,  I
rebase and squash all the temporary and trial and errors commits,  remove
the wip prefix and I do not rebase any more.

Never rebase a published feature branch,  but overall never EVER rebase the
master.

What I gain from this workflow is an increased productivity when trying
different things.

But I should never affect the other work and time with my rebasing

**Comment by ngeiswei** [comment]
I haven't touched that page in a very long time.  It current suggests
doing a rebase; that should probably be removed.   It should probably
suggest that pushes should be done often.

--linas

**Pull request closed without merging**
