### PR TITLE
change InheritanceLink to EvaluationLink

### PR DESCRIPTION
**Pull request by misgeatgit**
@cosmoharrigan or @AmeBel  can you review this?

### CODE REVIEW

**Comment by williampma** [comment]
Humm... I thought the file is for testing PLN "deduction"...  while the change is the correct representation, does it not affect the example?

**Comment by AmeBel** [comment]
Except the deduction that Peter moves all should be fine.

**Comment by williampma** [comment]
Might be just better to change (PredicateNode "Moves") to (ConceptNode "Movable") to keep both correct representation and all the deduction... but I guess that's not a major problem.

Does this change affect the testing of #1380?

**Comment by misgeatgit** [comment]
@williampma It won't affect that. I just happen to see it while I was inspecting the outputs.

**Pull request merged**
