### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by StrangeTcy**
Added some instructions to make it work.

### CODE REVIEW

**Comment by linas** [comment]
umm, this needs to be rebased onto `README.md`

**Comment by linas** [comment]
Hi @StrangeTcy you made some changes to this file but then renamed it to `README.md` and so now this pull req won't merge properly.  Care to update this pull req, so that the changes go into the new file?

**Comment by StrangeTcy** [comment]
I should do that, yes.

**Comment by linas** [comment]
Resolved in commit 7d8862eb1dfa459ca9d5a3248cd28d928496dc5c

**Pull request closed without merging**
