### PR TITLE
Possible fix for miner bug opencog/atomspace#2159

### PR DESCRIPTION
**Pull request by linas**
I have not tested this, but based on problem description in opencog/atomspace#2159, this should fix the problem.  Please review, test and merge at leisure.

### CODE REVIEW

**Comment by ngeiswei** [comment]
@linas, thanks but it doesn't solve the problem because, although it prints the solutions, as soon as the temporary atomspace is popped then the solutions disappear again.

But I don't think it is a bug now that I understand how guile deals with atomspace references. Instead I should redesign the API, like probably copying the results in the user's atomspace or something.

I'm fine with the behavior itself (deleting unreferenced atomspaces) I just think it should be better documented. To that end I have added a word of warning in https://wiki.opencog.org/w/Scheme#cog-set-atomspace.21, and will do that in `cog-set-atomspace` and `cog-pop-atomspace` docstrings.

**Comment by ngeiswei** [comment]
BTW, @linas, could have slightly more descriptive branch names (than `mi` for instance), it would make browsing your branches a bit easier. And branch names are stored in the git history so it's an extra reason to have them minimally informative.

**Comment by ngeiswei** [comment]
Closing as it doesn't properly address the problem. But it helped, thanks!

**Comment by linas** [comment]
What's the problem? `miner-utils.scm` has an obvious bug in it. This fixes the obvious bug. 

Are you telling me that after applying this patch, you still get some other crash?  If so, maybe a new bug report is in order?

**Comment by linas** [comment]
> how guile deals with atomspace references

This is how *any* garbage-collected or reference-counted language or library deals with *any* reference; its nothing particular to the atomspace.  Whenever there's some object, and there are no remaining references to it, it is fair game for finalization.

**Comment by linas** [comment]
The pull req opencog/atomspace#2164 is attempting to force the issue.  Currently, for me, all unit tests pass, so I'm guessing this particular utility is not currently tested.

**Comment by ngeiswei** [comment]
This fix has 2 problems
1. It doesn't return the solution set
2. Even if modified to return it then the solution set disappears after the temporary atomspace is popped.

The problem requires to modify the user API, so it is best left for another PR that I'll take care of. I know where I'm going now. Thanks.

**Pull request closed without merging**
