### PR TITLE
Copy rule files to build dir

### PR DESCRIPTION
**Pull request by misgeatgit**

### CODE REVIEW

**Comment by williampma** [comment]
Umm.. why?  Didn't we undo this before? I thought the .json is supposed to look at the DEFAULT_MODULE_PATH.

**Comment by misgeatgit** [comment]
It wasn't loading for me.

**Comment by williampma** [comment]
Then shouldn't it be fixed in the loading code?  It just seems a bad idea to copy these stuff to the build directory.

**Comment by misgeatgit** [comment]
OK, Appending opencog to the existing path seems to work. I will revert this one.

**Comment by williampma** [comment]
Ok, thanks!

**Pull request merged**
