### PR TITLE
Exclamatory  speech act

### PR DESCRIPTION
**Pull request by rodsol**
add exclamatory tag

### CODE REVIEW

**Comment by bgoertzel** [comment]
BTW, I think the microplanner does not yet handle interjections or
imperatives...


On Mon, Aug 3, 2015 at 12:01 PM, Rodas Solomon <notifications@github.com>
wrote:

> add exclamatory tag
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/opencog/opencog/pull/1697
> Commit Summary
>
>    - Exclamatory speech act
>
> File Changes
>
>    - *M* opencog/nlp/relex2logic/rule-helpers.scm
>    <https://github.com/opencog/opencog/pull/1697/files#diff-0> (4)
>
> Patch Links:
>
>    - https://github.com/opencog/opencog/pull/1697.patch
>    - https://github.com/opencog/opencog/pull/1697.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/pull/1697>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by williampma** [comment]
Why changed from InterjectiveSpeechAct to ExclamatorySpeechAct?  Any specific reason?

And what's the expected output of interjective sentence?  Is there still an EvaluationLink somewhere for the subject and verb?

**Comment by rodsol** [comment]
On Wed, Aug 5, 2015 at 6:35 AM, William Ma <notifications@github.com> wrote:

> Why changed from InterjectiveSpeechAct to ExclamatorySpeechAct? Any
> specific reason?
>
I don't mean to change it. I was just adding a speech act tag for those
sentence ... Since there is no rule for those sentence in the current R2L

BTW, what is the difference between them ( InterjectiveSpeechAct and
ExclamatorySpeechAct)

**Comment by rodsol** [comment]
oh sorry ... i didn't see ur link  https://github.com/opencog/opencog/blob/master/opencog/nlp/microplanning/main.scm#L389
i was replying from my email

**Comment by linas** [comment]
yes, what is the difference between InterjectiveSpeechAct and ExclamatorySpeechAct and are both really needed?

**Comment by bgoertzel** [comment]
Conceptually, an exclamation is just one kind of interjection...

For instance if I have a terrible stomach-ache and moan
"Owwwhhhhhuuugghhhh..." slowly and quietly while on the verge of dying,
this is not really an exclamation (it's too calm, quiet and slow), but it
is definitely an interjection...

-- Ben

On Wed, Aug 5, 2015 at 9:21 PM, Linas Vepštas <notifications@github.com>
wrote:

> yes, what is the difference between InterjectiveSpeechAct and
> ExclamatorySpeechAct and are both really needed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/pull/1697#issuecomment-128098689>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by williampma** [comment]
As far as I can tell, R2L should only output 4 different types of SpeechAct (first specified at http://wiki.opencog.org/w/Microplanner )

* Declarative
* Interrogative
* Imperative
* Interjective

I don't know where ExclamatorySpeechAct came from.  Is it from the Dialogue system design?  The SpeechAct defined in that document is different from what should be outputted by R2L I think.  The usage of the term "SpeechAct" is different.

**Comment by williampma** [comment]
Well, actually, even interrogative split into

* TruthQuerySpeechAct
* InterrogativeSpeechAct

in which case special handling is needed in the microplanner.

**Comment by bgoertzel** [comment]
The Dialogue System design has 40+ speech acts in it !!

Ruiting, Rodas and I have a devious plan to label sentences produced by
users with one of these 40+ speech act labels (using a statistical model
trained on a corpus of sentences labeled by speech act...)

We can discuss tomorrow F2F

Perhaps it is best to use a different terminology for the handful of
sentence types recognized by RelEx, and the 40+ speech acts used in the
dialogue system design?

ben



On Mon, Aug 10, 2015 at 5:59 AM, William Ma <notifications@github.com>
wrote:

> As far as I can tell, R2L should only output 4 different types of
> SpeechAct (first specified at http://wiki.opencog.org/w/Microplanner )
>
>    - Declarative
>    - Interrogative
>    - Imperative
>    - Interjective
>
> I don't know where ExclamatorySpeechAct came from. Is it from the Dialogue
> system design? The SpeechAct defined in that document is different from
> what should be outputted by R2L I think. The usage of the term "SpeechAct"
> is different.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/pull/1697#issuecomment-129285596>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by anitzkin** [comment]
It might not be a bad idea to distinguish, at this stage, between form and
function.  Relex classifies speech-acts according to their form. That
information will still be available to the dialogue management system.  But
the 40+ speech-act types include many classified in terms of their
pragmatic function, where the form of the utterance is only statistically
related to its speech-act function.  In other words, a sentence
interrogative in form, such as "Why don't you tell me about X" could be
imperative in function, or a variety of other things, I imagine.  That
classification would hopefully be possible based based on the statistical
model.You want to retain both bits of knowledge -- whether imperative,
interrogative, etc. in form, and the dialogue manager's guess at its
function.

**Pull request closed without merging**
