### PR TITLE
Openpsi - variable decay to baseline values 

### PR DESCRIPTION
**Pull request by eddiemonroe**
Internal psi variables will slowly move toward their baseline values absent of influence from external factors.

### CODE REVIEW

**Comment by ngeiswei** [comment]
Should this PR be closed, or it is to be merged? (the commits 8c824d8 to 73d6d19 look a bit suspicious).

**Comment by eddiemonroe** [comment]
hi @ngeiswei, this PR is to be merged. The commits you reference were merges of the master branch into the openpsi branch (from "git pull origin master" while in the openpsi branch), so these changes are already in master. The changes for this pull request are just in 4 files in the opencog/openpsi directory here https://github.com/opencog/opencog/pull/2607/files. 

Though, I see the jenkins check failed--not sure what that is about as it is building fine on my machine, but checking into it.

**Comment by eddiemonroe** [comment]
Oh, looks like these checks are commonly failing and not related to the openpsi code. 
4:ShellUTest
34:DimEmbedUTest

**Comment by linas** [comment]
ShellUTest has been passing great until recently. Any clue what broke it?

DimEmbed is unused and unmaintained, someone needs to go in there and modernize the code. I think it got broken by general work on attention values and attention allocation.

**Comment by ngeiswei** [comment]
But unless you have commits before the merges, git should have done a mere fast-forward merge and these merge commits should not appear.

Also, I tried to merge your branch into my local master, and these merge commits still appear. Now if you have commits before these merges I believe they should still appear in github, if they don't, it's bad because it obfuscate the reviewing process. Maybe you modified your local master before merging it into your branch. I'm confused.

@eddiemonroe do you remember anything else beside doing `git pull origin master`?

**Comment by ngeiswei** [comment]
@eddiemonroe Weird you don't have a master in your branches.

**Comment by ngeiswei** [comment]
I know what went wrong. Your master (or whatever branch you use as your master) is "misaligned" with the upstream master. What happened is that during your last PR, you merged the upstream master back your branch after creating the PR but *before* it got merged to upstream, as the git history shows. Commit 8c824d8 (you merging upstream to your branch) occurs before commit 51ce552 (Manhin merging your branch to upstream), but the former wasn't pushed to origin before the later, so git couldn't properly merge them. Then you probably kept on working with that branch.

Anyway, my suggestion is that you start from a fresh master, checked out from upstream, then cherry pick your 2 commits on top of it, recreate a PR with that.

**Comment by eddiemonroe** [comment]
thanks @ngeiswei for figuring out the issue here with the merges! I did your suggestion of cherry picking the commits on a fresh master and created a new PR #2616. Closing this one.

**Pull request closed without merging**
