### PR TITLE
Partial cleanup of Openpsi

### PR DESCRIPTION
**Pull request by AmeBel**
Includes:
* directory restructuring
* 3 agents are able to run independent of the embodiment code and moses
*  a couple of improvements on the TimeServer class

Todo:
* refactor the rest of the agents
* write a simple OpenPsi rule definition
* add unit tests

### CODE REVIEW

**Comment by AmeBel** [comment]
@misgeatgit @ngeiswei please comment, thanks :smile:

**Comment by bgoertzel** [comment]
Woo hoo, thanks Amen!  ;)

On Thu, Jun 18, 2015 at 5:00 PM, Amen Belayneh <notifications@github.com>
wrote:

> Includes:
>
>    - directory restructuring
>    - 3 agents are able to run independent of the embodiment code and moses
>    - a couple of improvements on the TimeServer class
>
> Todo:
>
>    - refactor the rest of the agents
>    - write a simple OpenPsi rule definition
>    - add unit tests
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/opencog/opencog/pull/1649
> Commit Summary
>
>    - move OpenPsi related code to a separate directory
>    - update CMakeLists.txt with the move
>    - Add note on freeing the timeserver off the spaceserver
>    - add CMakeList entry for openpsi demand-updater
>    - a loading OpenPsi Module
>    - partial cleanup of OpenPsi demanupdater agent
>    - demand updater agent is running
>    - add PSIDEMAND entry to configuration file
>    - change paramater type to avoid implicit casting
>    - add constructor to timeserver independent of spaceserver
>    - prelimenary cleanup of the action selection agent
>    - addditional clean up on action selection
>    - add missing varaible and whitespace cleanups
>    - comment out methods that depend on moses
>    - action-selection agent runs on cogserver
>    - remove Implication Link from find_psi_rule
>    - make openpsi module be pre-loaded
>    - remove implication link & add a wrong fix for error
>    - get action selection agent to run in empty atomspace
>    - assortment of small changes
>    - setup for working on moudlator updating agent
>    - add timestamp of atom to temporal table
>    - a running modulator updater agent
>    - add TODO on TimeServer class
>    - add a README.md
>    - remove TimeServer
>
> File Changes
>
>    - *M* lib/opencog.conf
>    <https://github.com/opencog/opencog/pull/1649/files#diff-0> (14)
>    - *M* opencog/dynamics/CMakeLists.txt
>    <https://github.com/opencog/opencog/pull/1649/files#diff-1> (1)
>    - *A* opencog/dynamics/openpsi/CMakeLists.txt
>    <https://github.com/opencog/opencog/pull/1649/files#diff-2> (9)
>    - *A* opencog/dynamics/openpsi/OpenPsiModule.cc
>    <https://github.com/opencog/opencog/pull/1649/files#diff-3> (60)
>    - *A* opencog/dynamics/openpsi/OpenPsiModule.h
>    <https://github.com/opencog/opencog/pull/1649/files#diff-4> (57)
>    - *A* opencog/dynamics/openpsi/PsiActionSelectionAgent.cc
>    <https://github.com/opencog/opencog/pull/1649/files#diff-5> (421)
>    - *R* opencog/dynamics/openpsi/PsiActionSelectionAgent.h
>    <https://github.com/opencog/opencog/pull/1649/files#diff-6> (90)
>    - *R* opencog/dynamics/openpsi/PsiDemandUpdaterAgent.cc
>    <https://github.com/opencog/opencog/pull/1649/files#diff-7> (114)
>    - *R* opencog/dynamics/openpsi/PsiDemandUpdaterAgent.h
>    <https://github.com/opencog/opencog/pull/1649/files#diff-8> (53)
>    - *R* opencog/dynamics/openpsi/PsiFeelingUpdaterAgent.cc
>    <https://github.com/opencog/opencog/pull/1649/files#diff-9> (0)
>    - *R* opencog/dynamics/openpsi/PsiFeelingUpdaterAgent.h
>    <https://github.com/opencog/opencog/pull/1649/files#diff-10> (0)
>    - *R* opencog/dynamics/openpsi/PsiModulatorUpdaterAgent.cc
>    <https://github.com/opencog/opencog/pull/1649/files#diff-11> (192)
>    - *R* opencog/dynamics/openpsi/PsiModulatorUpdaterAgent.h
>    <https://github.com/opencog/opencog/pull/1649/files#diff-12> (42)
>    - *R* opencog/dynamics/openpsi/PsiRelationUpdaterAgent.cc
>    <https://github.com/opencog/opencog/pull/1649/files#diff-13> (0)
>    - *R* opencog/dynamics/openpsi/PsiRelationUpdaterAgent.h
>    <https://github.com/opencog/opencog/pull/1649/files#diff-14> (0)
>    - *R* opencog/dynamics/openpsi/PsiRuleUtil.cc
>    <https://github.com/opencog/opencog/pull/1649/files#diff-15> (438)
>    - *R* opencog/dynamics/openpsi/PsiRuleUtil.h
>    <https://github.com/opencog/opencog/pull/1649/files#diff-16> (142)
>    - *A* opencog/dynamics/openpsi/README.md
>    <https://github.com/opencog/opencog/pull/1649/files#diff-17> (31)
>    - *R* opencog/dynamics/openpsi/action_selection.scm
>    <https://github.com/opencog/opencog/pull/1649/files#diff-18> (341)
>    - *R* opencog/dynamics/openpsi/demand_updaters.scm
>    <https://github.com/opencog/opencog/pull/1649/files#diff-19> (0)
>    - *R* opencog/dynamics/openpsi/feeling_updaters.scm
>    <https://github.com/opencog/opencog/pull/1649/files#diff-20> (0)
>    - *R* opencog/dynamics/openpsi/modulator_updaters.scm
>    <https://github.com/opencog/opencog/pull/1649/files#diff-21> (0)
>    - *R* opencog/dynamics/openpsi/psi_util.scm
>    <https://github.com/opencog/opencog/pull/1649/files#diff-22> (444)
>    - *R* opencog/dynamics/openpsi/rules_core.scm
>    <https://github.com/opencog/opencog/pull/1649/files#diff-23> (0)
>    - *R* opencog/dynamics/openpsi/stimulus_updaters.scm
>    <https://github.com/opencog/opencog/pull/1649/files#diff-24> (0)
>    - *M* opencog/embodiment/AtomSpaceExtensions/AtomSpaceUtil.cc
>    <https://github.com/opencog/opencog/pull/1649/files#diff-25> (21)
>    - *M*
>    opencog/embodiment/Control/OperationalAvatarController/CMakeLists.txt
>    <https://github.com/opencog/opencog/pull/1649/files#diff-26> (12)
>    - *D*
>    opencog/embodiment/Control/OperationalAvatarController/PsiActionSelectionAgent.cc
>    <https://github.com/opencog/opencog/pull/1649/files#diff-27> (874)
>    - *M* opencog/spacetime/TimeServer.cc
>    <https://github.com/opencog/opencog/pull/1649/files#diff-28> (23)
>    - *M* opencog/spacetime/TimeServer.h
>    <https://github.com/opencog/opencog/pull/1649/files#diff-29> (27)
>
> Patch Links:
>
>    - https://github.com/opencog/opencog/pull/1649.patch
>    - https://github.com/opencog/opencog/pull/1649.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/pull/1649>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by AmeBel** [comment]
@bgoertzel example rules are not defined so it doesn't do anything yet. That is what I am working on now.

**Comment by AmeBel** [comment]
Please note that this changes will break the OAC . Refer to https://github.com/opencog/opencog/blob/master/opencog/embodiment/Control/OperationalAvatarController/OAC.h#L64

I just observed on the mailing list that GSOC students are using it, so may be I could revert back the old agents and move them in the old directory and wrap a namespace around the refactored agents or modify the header guard to avoid conflicts, need help on this one.

**Comment by linas** [comment]
who is using OAC? Is this Brad and Yi-shan, for the minecraft work?

**Comment by AmeBel** [comment]
@linas I believe so. Aren't they?

**Comment by linas** [comment]
no clue.  Ask them ...

**Comment by bgoertzel** [comment]
I think they are not ...

Yishan is using 3dspacemap, but separately from oac I believe

**Comment by misgeatgit** [comment]
You have removed a lot of code. I am not sure if that is the right way to start the refactoring.

**Comment by linas** [comment]
so if brad is not using this ts oK to merge, right?

**Comment by bgoertzel** [comment]
I think in this case removing the code WAS the right way to start ... The
only good alternative would have been to remove all the code and start from
scratch ...

**Comment by misgeatgit** [comment]
Okay, to be clear  I was thinking if doing it from scratch could be done in a separate directory.

**Comment by bgoertzel** [comment]
Yeah ... But nobody will ever use the prior openpsi code again, so it
doesn't matter ...

**Comment by misgeatgit** [comment]
I agree in that case.

**Comment by ngeiswei** [comment]
I'm trusting @AmeBel on this. The changes look mainly structural anyway and I seem to approve them.

@AmeBel ideally you'd have re-enabled the openpsi unit test first, but for having tried for so many hours and failing I understand that you don't want to go through that pain. My advice would be to re-introduce unit tests as early as possible, when starting doing the real implementation changes.

Perhaps someone is relying on the OAC, he/she probably shouldn't, so I'm merging.

**Comment by AmeBel** [comment]
@ngeiswei I will add the unit tests as soon as I get the example case running.

**Comment by AmeBel** [comment]
Thanks

**Pull request merged**
