### PR TITLE
Update the control policy base class

### PR DESCRIPTION
**Pull request by williampma**

### CODE REVIEW

**Comment by AmeBel** [comment]
should the rules be in the conf file or a json file ?

**Comment by williampma** [comment]
The ForwardChainer load .json by default.

I am just updating the base class for consistency.

**Comment by misgeatgit** [comment]
I prefer json. conf file is designed for key values.You have to do a lot of string manipulation to support other ways of description in a conf file.

**Comment by misgeatgit** [comment]
The ForwardChainer load .json by default.
I am just updating the base class for consistency.

>Yes, the default is json. we might end up throwing the other one.

**Comment by AmeBel** [comment]
@misgeatgit when you say '.. end up throwing .." does it imply there are cases were it is used?

**Comment by misgeatgit** [comment]
@Amebel  No it is not being used except for the fact that it is a base class for the json loader class.It can be easily refactored out when we really want to do so.But its not a priority now.

**Comment by AmeBel** [comment]
thanks, got it

**Comment by linas** [comment]
After pulling and building this commit, I still cannot run DefaultForwardChainerCBUTest It always fails because it cannot find the json file.  I tried to run it three different ways:
```
cd $PROJECT_SRC_DIR;  ./build/tests/reasoning/RuleEngine/DefaultForwardChainerCBUTest
cd build; ./tests/reasoning/RuleEngine/DefaultForwardChainerCBUTest
cd tests/reasoning/RuleEngine;   ./DefaultForwardChainerCBUTest
```
all three fail with the error:  `DefaultForwardChainerCBUTest.cxxtest:65: Error: Expected (1 == rule.size()), found (1 != 0)`  which means that it cannot read the json file.

**Comment by misgeatgit** [comment]
@linas as I mentioned in another thread its because of the choose_rule function not behaving properly.I am fixing that.

**Pull request merged**
