### PR TITLE
Fix moses segregation

### PR DESCRIPTION
**Pull request by ngeiswei**
Fixed a bunch of compile errors to support the new standalone MOSES.

I'm still struggling with linking error:

```
/usr/bin/ld: ../../../util/libcogutil.so: undefined reference to symbol '_ZN5boost9re_detail12perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE5matchEv'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libboost_regex.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
I don't understand yet but I'm merging already so others can look at it if they want (it was still breaking anyway).

### CODE REVIEW

**Comment by linas** [comment]
I've resolved this. I've also split out cogutil from moses and put it in its own project in github. I've mostly split it out of opencog as well, -- everything compiles, but, due to a variety of hard-coded paths and etc a large fraction of unit tests fail because assorted modules don't load.  The module load path stuff is a mess.  Care to take stab at it?  The current state of opencog is here:   https://github.com/opencog/opencog/branches  its the branch called "util-remove".

**Comment by linas** [comment]
err, looks like I accidentally pushed to master. I need to revert that. I'm getting tired.

**Comment by linas** [comment]
OK, I reverted all the damage that I accidentaly did, so `master` on opencog should compile and test great with and without moses.  The not-quite working versions with cogutil removed is as mentioned before: here  https://github.com/opencog/opencog/branches its the branch called "util-remove".

**Comment by ngeiswei** [comment]
@linas I didn't manage to make progress on that (just fixed a compile error related to MOSES embodiment). I'm resuming work on it. Have you done any progress?

**Comment by ngeiswei** [comment]
Well, actually I'm making progress (it's crazy how a little nap can expand your consciousness), I'm pretty sure it has to do with DEFAULT_MODULE_PATHS, the CMAKE_INSTALL_PREFIX is not the same anymore as it's using cogutils'...

**Comment by linas** [comment]
OK,  I just pushed somethig to cogutils that extends the search patchs pull
now

**Comment by linas** [comment]
I changed the search paths in cogutils/opencog/util/files.cc and now all
opencog unit tests pas just fine.

So I thought I would try again, this time with moses installed, and ... now
I am getting the weird shared library DSO message again, which went away
yesterday. ...

**Comment by ngeiswei** [comment]
Regarding DSO just pull the last util-remove.

**Comment by ngeiswei** [comment]
Regarding DEFAULT_MODULE_PATHS, maybe it's better to move it to where modules are compiled (currently in the opencog repo), rigth?

**Comment by linas** [comment]
Yes. I hacked the solution last night while I was tired and ran out of
energy for anything better .

**Comment by ngeiswei** [comment]
OK, I'll move DEFAULT_MODULE_PATHS to CogServer.{h,cc}, where I think it makes more sense.

**Comment by linas** [comment]
Yes, except half of the unit tests don't use the cogserver

**Comment by linas** [comment]
and the goal is to depend on the cogserver less and less

**Comment by ngeiswei** [comment]
But the cogserver does load the modules, right?
```
CogServer::loadModule
```

**Comment by ngeiswei** [comment]
though of course if the plan is to kill the cogserver (better do it now while it's not self-aware), then I guess it matters little to have DEFAULT_MODULE_PATHS defined in it. So the question is what is gonna load the modules after?

**Comment by ngeiswei** [comment]
Anyway, all tests pass I guess we can merge util-remove to the master.

**Comment by linas** [comment]
if it works, then merge

**Comment by ngeiswei** [comment]
Merging... (have to figure out how to deal with the delete conflicts).

**Pull request merged**
