### PR TITLE
some remnants from pattern miner removal in #3533

### PR DESCRIPTION
**Pull request by ferrouswheel**

### CODE REVIEW

**Comment by linas** [comment]
The new patternminer does not need custom types any more?

**Comment by ferrouswheel** [comment]
@ngeiswei will have to confirm that. This just fixes the broken symbols, so that tests "work" again - i.e. are in the state they were in before #3533.

**Comment by linas** [comment]
actually, this is a variant of the spacetime atoms bug - even if the new patternminer did need new atom types, this would not be the right place to initialize them,

**Comment by ngeiswei** [comment]
The new pattern miner doesn't need new atom types, instead it relies on scoping and quotation for reflection, discovered patterns are essentially pattern matcher queries.

**Pull request merged**
