### PR TITLE
Fix atomspace in REST API

### PR DESCRIPTION
**Pull request by GarethNelson**
Fix for issue #1625

### CODE REVIEW

**Comment by cosmoharrigan** [comment]
Thanks for looking into this; some comments:

The changes to opencog.conf are unrelated to the fix.

The primary changes are those on line 5 and line 54 of apiatomcollection.py; the pull request could be simplified to only contain those 2 line changes.

But, actually, shouldn't that assignment happen in the ```new``` method, on line 25?

I wonder if the nose tests pass after making that change?
```
> cd ~/opencog/tests/python/restapi
> python2.7 -m nose test_restapi.py --nologcapture
```

**Comment by kim135797531** [comment]
Hi @cosmoharrigan,

Assignment of AtomSpace happen in the `new` method, but it does not contain any of method about atomspace due to bug. Please review my pull request #1632 attempt to fix this problem.

**Comment by AmeBel** [comment]
Hi @kim135797531 please rebase so I can test it before merge. Thanks

**Comment by kim135797531** [comment]
Hi @AmeBel,
Sorry but could I ask you which branch to rebase? My pull request was making REST API to re-work and it was merged. (But it didn't resolve the fail tests about REST API)

**Comment by AmeBel** [comment]
woops,  @kim135797531 sorry for bothering you . 

@GarethNelson please rebase so I can test it before merge. Thanks

**Pull request merged**
