### PR TITLE
Fix for bug #1478

### PR DESCRIPTION
**Pull request by linas**

### CODE REVIEW

**Comment by williampma** [comment]
Thanks, Linas.

**Comment by linas** [comment]
yah, my fix seems to break EinsteinUTest!!? which I did  not discover until after merging it. I'm unlike to nail it today, though.

**Comment by linas** [comment]
Never mind. I just fixed that...

**Comment by linas** [comment]
yeah, the atom-table add code s kind of hairy and hard to follow... :-(

**Pull request merged**
