### PR TITLE
Experimental number-valued atoms

### PR DESCRIPTION
**Pull request by linas**
This is an demo prototype showing one way in which number-valued NumberNodes could be accomodated in the AtomSpace.  The demo "works" in the sense that you can now say
```
  (cog-evaluate! (NotLink (GreaterThanLink (NumberNode 3)
     (PlusLink (NumberNode 6) (TimesLink (NumberNode 7) (NumberNode 11))))))
```
and get back TRUE_TV.  However, the code is very inefficient, were you to compare it to the equivalent combo code.   There are many reasons for this, and the README lists some of them.  Thus, this really should be considered to be "experimental" code, rather than the 'one true way'.

### CODE REVIEW

**Comment by ngeiswei** [comment]
Very interesting. In the README you say that the main cost is with inserting the atom in the atomspace, but depending on the context this cost could be little compared to say evaluating a program over thousands of inputs, wouldn't it?

I remember you also said that an atom can be defined without being inserted in the atomspace.

Otherwise, if the evaluation itself cost much more than with the combo interpreter, I guess the combo code can be kept around, maybe we don't have a choice, we need the 2 sides of the coin.

**Comment by ngeiswei** [comment]
Linas, you haven't merged, I'll let you do it in case it was intentional.

**Comment by linas** [comment]
Yes, you can use atoms without placing them in the atomspace, as long as you keep things simple. Both python and scheme often/usually need atoms to be in an atomspace to work with them; this is partly a historical accident, and partly a snow-ball effect coming from other requirements. Dis-entangling this would take a fairly large effort; there are various spots where some tough decisions would be needed.

**Comment by bgoertzel** [comment]
On Wed, Mar 11, 2015 at 4:39 AM, ngeiswei <notifications@github.com> wrote:

> Very interesting. In the README you say that the main cost is with
> inserting the atom in the atomspace, but depending on the context this cost
> could be little compared to say evaluating a program over thousands of
> inputs, wouldn't it?
>
> I remember you also said that an atom can be defined without being
> inserted in the atomspace.
>
> Otherwise, if the evaluation itself cost much more than with the combo
> interpreter, I guess the combo code can be kept around, maybe we don't have
> a choice, we need the 2 sides of the coin.
>

If the evaluation itself is a lot more expensive in Atomspace than in
Combo, then we could still make the MOSES population a set of Atoms if we
want to --- but then associate with certain sub-hypergraphs a "compiled
version" (Combo) that is optimized for faster execution.    If the
Atomspace version of the sub-hypergraph changes then the compiled version
has to be re-generated....

For instance in the case of

  (cog-evaluate! (NotLink (GreaterThanLink (NumberNode 3)
     (PlusLink (NumberNode 6) (TimesLink (NumberNode 7) (NumberNode 11))))))

we could have the NotLink associated with a Combo tree...

Or would we need a SetLink that links to all the Atoms in the
expression, and then associate the Combo tree with that SetLink?

ben

**Comment by ngeiswei** [comment]
Yes, it's actually an idea that can be used more broadly, have a "compiler", that turns a program as hypergraph into a compiled GSN (in combo, scheme, Python, or maybe even binary code using LLVM).

This makes me realize something, we probably want to keep combo as it is, its interpreter, etc, just remove the current to-be-obsolete  action/perception vocabulary part, and add support for Atoms (including GSN, etc), which will be a completely substitute for action/perception.

Well, this has been in the original design for a while, now is the time.

**Comment by linas** [comment]
Technically, its a lot easier to stick atoms into combo vertexes, than it would be to turn atoms into combo vertexes.

If you follow this route, then I think you want to stick Handles (not Atoms and not AtomPtr's) into combo vertexes.

**Comment by bgoertzel** [comment]
On Thu, Mar 12, 2015 at 6:21 AM, Linas Vepštas <notifications@github.com>
wrote:

> Technically, its a lot easier to stick atoms into combo vertexes, than it
> would be to turn atoms into combo vertexes.
>
> If you follow this route, then I think you want to stick Handles (not
> Atoms and not AtomPtr's) into combo vertexes.
>

So that e.g. the Combo Vertex for "+" would do addition in its usual way,
but would also contain the Handle of the "+" GroundedSchemaNode?

ben

**Comment by bgoertzel** [comment]
On Thu, Mar 12, 2015 at 4:53 AM, ngeiswei <notifications@github.com> wrote:

> Yes, it's actually an idea that can be used more broadly, have a
> "compiler", that turns a program as hypergraph into a compiled GSN (in
> combo, scheme, Python, or maybe even binary code using LLVM).
>
> This makes me realize something, we probably want to keep combo as it is,
> its interpreter, etc, just remove the current to-be-obsolete
> action/perception vocabulary part, and add support for Atoms (including
> GSN, etc), which will be a completely substitute for action/perception.
>

yeah, so that for a Combo tree Vertex to refer to the "blink" action, it
would contain the Handle of the "blink" GSN ... ?


> Well, this has been in the original design for a while, now is the time.
>

Actually next month is probably the time -- now is the time for you to get
some examples of PLN doing something cool with exported MOSES program trees
;)

But yeah, sure, "now" is a variable-width entity !!

**Comment by linas** [comment]
> So that e.g. the Combo Vertex for "+" would do addition in its usual way,
> but would also contain the Handle of the "+" GroundedSchemaNode?
>

If the goal is to have one-to-one, side-by-side layouts, then it would have
to point at PlusLink

If not that, then some sort of implicit understanding that when a
GroundedSchemaNode  occurs in combo, there is an implicty
ExecutionOutputLink just above it.

I have not really looked at or thought about how to define "user-defined
functions" in combo.

I'm also a little hazy about the desired use-case.  What exactly, do we
hope to do?  Nil's "compiler" can "easiy" turn combo trees into opencog
atoms. Writing something that does the reverse translation is not hard,
either .. depending on what you want to do.

If you want to support GroundedSchemaNode "scm: anything" or
GroundedSchemaNode "py: anything" in combo/moses ... that's possible, but
... ?? why? (Just because its cool doesn't mean its a good idea..)

There's a diferent moses issue I don't really understand: at the bottom of
those combo trees are always column names of columns from some table.  What
is the atomspace equivalent of these?

**Comment by bgoertzel** [comment]
>
> I'm also a little hazy about the desired use-case. What exactly, do we
> hope to do? Nil's "compiler" can "easiy" turn combo trees into opencog
> atoms. Writing something that does the reverse translation is not hard,
> either .. depending on what you want to do.



My near-term use case is

-- importing some Combo programs into the Atomspace

-- using PLN to learn some new Boolean program trees, based on these Combo
programs plus other information

-- exporting the learned Boolean program trees back into MOSES to seed a
new deme

All this of course can be done without hooking MOSES and the Atomspace
together in any fancy way, just by importing/exporting...

OTOH a closer linkage would make it nicer...

- Ben

**Comment by ngeiswei** [comment]
On 03/11/2015 11:21 PM, Linas Vepštas wrote:
> Technically, its a lot easier to stick atoms into combo vertexes, than
> it would be to turn atoms into combo vertexes.
>
> If you follow this route, then I think you want to stick Handles (not
> Atoms and not AtomPtr's) into combo vertexes.

Sounds good. Although I have a question:

Do Handle really uniquely identify an Atom? I mean that if MOSES is 
storing its atoms on a local AtomSpace, and then it wants to copy the 
combos (with those atoms) to another AtomSpace, are the Handle gonna 
stay the same (same UUID), or is there some translation needed?

**Comment by ngeiswei** [comment]
On 03/12/2015 01:50 AM, bgoertzel wrote:
> On Thu, Mar 12, 2015 at 4:53 AM, ngeiswei <notifications@github.com> wrote:
>
>  > Yes, it's actually an idea that can be used more broadly, have a
>  > "compiler", that turns a program as hypergraph into a compiled GSN (in
>  > combo, scheme, Python, or maybe even binary code using LLVM).
>  >
>  > This makes me realize something, we probably want to keep combo as it is,
>  > its interpreter, etc, just remove the current to-be-obsolete
>  > action/perception vocabulary part, and add support for Atoms (including
>  > GSN, etc), which will be a completely substitute for action/perception.
>  >
>
> yeah, so that for a Combo tree Vertex to refer to the "blink" action, it
> would contain the Handle of the "blink" GSN ... ?

Exactly. This could be a nice substitute for the WorldWrapper code. 
There are issues however

1. It maybe introduces run-time inefficiencies.

2. While learning and running evaluation in its imaginary world, the 
GSNs are gonna have to trigger different things. Maybe they can just 
point to different code, for instance GSN "py: blink" could be 
reimplemented to run in this imaginary world, and that file would be 
loaded instead of the real world version

**Comment by ngeiswei** [comment]
On 03/12/2015 05:17 AM, Linas Vepštas wrote:
>  > So that e.g. the Combo Vertex for "+" would do addition in its usual way,
>  > but would also contain the Handle of the "+" GroundedSchemaNode?
>  >
>
> If the goal is to have one-to-one, side-by-side layouts, then it would have
> to point at PlusLink
>
> If not that, then some sort of implicit understanding that when a
> GroundedSchemaNode occurs in combo, there is an implicty
> ExecutionOutputLink just above it.
>
> I have not really looked at or thought about how to define "user-defined
> functions" in combo.

This is already fully supported (though MOSES doesn't use it), see

opencog/comboreduct/combo/procedure_call.{h,cc}

>
> I'm also a little hazy about the desired use-case. What exactly, do we
> hope to do? Nil's "compiler" can "easiy" turn combo trees into opencog
> atoms. Writing something that does the reverse translation is not hard,
> either .. depending on what you want to do.

Well, frankly it's rather anticipatory, we've just started experimenting 
with exporting combos in the AtomSpace, it just feels we'd need that, 
but we don't need it today (the first step is to get PLN reason about them).

>
> If you want to support GroundedSchemaNode "scm: anything" or
> GroundedSchemaNode "py: anything" in combo/moses ... that's possible, but
> ... ?? why? (Just because its cool doesn't mean its a good idea..)

As I said it could be a nice substitute for the WorldWrapper. That way 
MOSES can evaluate combos involving GSN (action/perception or whatnot).

>
> There's a diferent moses issue I don't really understand: at the bottom of
> those combo trees are always column names of columns from some table. What
> is the atomspace equivalent of these?

Good question. It's probably possible to export the fitness functions in 
the atomSpace as well, so you'd have a GSN or GPN that takes a combo, a 
list of inputs/outputs (ListLink of ListLink, whatever) and compute the 
fitness. That GSN could actually be an hypergraph using map or fold 
operators, etc. But again it's rather anticipatory, we don't need that 
today.

To be honest I'm kinda revisiting my earlier opinion that we can just 
move MOSES entirely in the AtomSpace, or maybe we can but, but just for 
efficiency reasons we may still want to keep the combo language and 
interpreter and other structures.

**Comment by linas** [comment]
On Thu, Mar 12, 2015 at 3:08 AM, ngeiswei <notifications@github.com> wrote:

>
>
> On 03/11/2015 11:21 PM, Linas Vepštas wrote:
> > Technically, its a lot easier to stick atoms into combo vertexes, than
> > it would be to turn atoms into combo vertexes.
> >
> > If you follow this route, then I think you want to stick Handles (not
> > Atoms and not AtomPtr's) into combo vertexes.
>
> Sounds good. Although I have a question:
>
> Do Handle really uniquely identify an Atom? I mean that if MOSES is
> storing its atoms on a local AtomSpace, and then it wants to copy the
> combos (with those atoms) to another AtomSpace, are the Handle gonna
> stay the same (same UUID), or is there some translation needed?
>

Whenever you place an atom into an atomspace, you are given a handle to it.
That is the handle that you should use (for that atom in that atomspace)

This solves multiple problems:

-- if you create two identical atoms, and put them into the same atomspace,
the returned hadnle for the second add will point at the first atom. (and
the first uuid)

-- If you loose or forget the handle, that's OK, as long as you remember
the name. If you remember the name, just ask the atomspace for it again.

-- if you create one atom and try to stick it into multiple independent
atomspaces, each atomspace will return the handle for its particular copy.
(each gets a different uuid)

-- the above does not hold when the atomspaces are not independent, but are
arranged as main-space & extension if there already is an atom in the main
space, and you try to put it into the extension, it won't go in there; you
just  get back the main handle.  the only things you can put in the
extension are atoms that are not yet in main.

(bad stuff happens if you put it into extension first, and main later. this
could be solved, but has not been yet)

Linas

**Pull request merged**
