### PR TITLE
Disable pattern miner utest

### PR DESCRIPTION
**Pull request by ngeiswei**
This is the only unit test that doesn't pass. I'm disabling it since it
might only start passing after a while.

### CODE REVIEW

**Comment by linas** [comment]
Only?  PLNRulesUTest has not passed in months. Not passing right now.

**Comment by ngeiswei** [comment]
They all pass for me, although I should say not all components are built on my system
```
The following components WILL NOT be built:
-----------------------------------------------
   REST             - REST Atomspace Publisher module.
   SpaceTime        - 3D Space-Time object tracker.
   Spatial          - Vizualisation of the 3D spacemap.
   NLP              - Natural Language Processing.
```

**Comment by linas** [comment]
Well, aren't you actively maintaining PLNRulesUTest ? I'll open a different bug, then.

**Comment by linas** [comment]
Bug #2487

**Pull request merged**
