### PR TITLE
Make Interaction Information algorithm work

### PR DESCRIPTION
**Pull request by kim135797531**
Finished working suggested in #1678. (Except python binding)

* Merge the template methods into header file.
  * C++ template can not be implemented in a cpp file. (if we want to avoid using a hacky method)
* Improve algorithm
  * Use a STL sort algorithm.
  * Remove boost library.
* Fix the bugs.
  * Remove a non-standard function 'atoi()'. Start to use the lexical_cast in boost lib.
  * Resolve the mismatched template types in algorithm.
  * Fix a bug related with variable range mistake.
* Stabilize the code.
  * Change 'int' in some parameters to 'long' to prevent the possible loss of data.
  * Change 'float' in some parameters to 'double' to prevent the possible loss of data.
  * Use an unique integer value to index the gram data.
  * Write 'inline' keyword to every template methods explicitly.
  * Remove the 'using namespace std;' statement.
  * Change the c-style library headers to cpp-style.
  * Fix the delete statement mistake in DataProvider's destructor.
* Improve the code style.
  * Location of brackets, columns size, ...
* Make a unit test with assert statements.

### CODE REVIEW

**Comment by misgeatgit** [comment]
@shujingke do you have any comments on what @kim135797531  has done?

**Comment by ngeiswei** [comment]
@kim135797531 that looks good to me. However you should add the output of the unit tests in the pull request message (it's a new policy to prevent from merging code that would break the master). Thanks.

**Comment by kim135797531** [comment]
@ngeiswei Thank you for your advice. My unit test doesn't produce any log(except debugging information). Here is overall output of the unit tests.

```
Test project /home/kdm/opencog/build/tests
      Start  1: SavingLoadingUTest
 1/38 Test  #1: SavingLoadingUTest ....................   Passed    0.06 sec
      Start  2: AtomSpacePublisherModuleUTest
 2/38 Test  #2: AtomSpacePublisherModuleUTest .........   Passed    5.10 sec
      Start  3: CogServerUTest
 3/38 Test  #3: CogServerUTest ........................   Passed    5.36 sec
      Start  4: AgentUTest
 4/38 Test  #4: AgentUTest ............................   Passed    0.05 sec
      Start  5: VisibilityMapUTest
 5/38 Test  #5: VisibilityMapUTest ....................   Passed    2.53 sec
      Start  6: HPASearchUTest
 6/38 Test  #6: HPASearchUTest ........................   Passed    0.12 sec
      Start  7: MathUTest
 7/38 Test  #7: MathUTest .............................   Passed    0.14 sec
      Start  8: TemporalUTest
 8/38 Test  #8: TemporalUTest .........................   Passed    0.03 sec
      Start  9: TemporalMapUTest
 9/38 Test  #9: TemporalMapUTest ......................   Passed    0.11 sec
      Start 10: TemporalTableUTest
10/38 Test #10: TemporalTableUTest ....................   Passed    0.09 sec
      Start 11: TimeServerUTest
11/38 Test #11: TimeServerUTest .......................   Passed    0.12 sec
      Start 12: AnaphoraTest
12/38 Test #12: AnaphoraTest ..........................***Failed    0.18 sec
      Start 13: PythonPLNTest
13/38 Test #13: PythonPLNTest .........................   Passed    0.10 sec
      Start 14: PLNRulesUTest
14/38 Test #14: PLNRulesUTest .........................***Failed    0.45 sec
      Start 15: PythonModuleUTest
15/38 Test #15: PythonModuleUTest .....................***Failed    0.24 sec
      Start 16: PyEvalUTest
16/38 Test #16: PyEvalUTest ...........................   Passed    0.04 sec
      Start 17: CythonServer
17/38 Test #17: CythonServer ..........................   Passed    0.12 sec
      Start 18: CythonMoses
18/38 Test #18: CythonMoses ...........................   Passed   57.61 sec
      Start 19: RestApiTest
19/38 Test #19: RestApiTest ...........................***Failed    0.39 sec
      Start 20: BlendingTest
20/38 Test #20: BlendingTest ..........................   Passed    5.15 sec
      Start 21: ForgettingAgentUTest
21/38 Test #21: ForgettingAgentUTest ..................   Passed    0.06 sec
      Start 22: HebbianUpdatingAgentUTest
22/38 Test #22: HebbianUpdatingAgentUTest .............   Passed    0.05 sec
      Start 23: ImportanceUpdatingAgentUTest
23/38 Test #23: ImportanceUpdatingAgentUTest ..........   Passed    0.08 sec
      Start 24: HebbianCreationModuleUTest
24/38 Test #24: HebbianCreationModuleUTest ............   Passed    1.05 sec
      Start 25: SimpleImportanceDiffusionAgentUTest
25/38 Test #25: SimpleImportanceDiffusionAgentUTest ...   Passed    0.12 sec
      Start 26: DimEmbedUTest
26/38 Test #26: DimEmbedUTest .........................   Passed    0.07 sec
      Start 27: StatisticsUTest
27/38 Test #27: StatisticsUTest .......................   Passed    0.01 sec
      Start 28: AtomSpaceUtilUTest
28/38 Test #28: AtomSpaceUtilUTest ....................   Passed    0.09 sec
      Start 29: RouterMessageUTest
29/38 Test #29: RouterMessageUTest ....................   Passed    0.02 sec
      Start 30: FileMessageCentralUTest
30/38 Test #30: FileMessageCentralUTest ...............   Passed    0.33 sec
      Start 31: MemoryMessageCentralUTest
31/38 Test #31: MemoryMessageCentralUTest .............   Passed    0.23 sec
      Start 32: StringMessageUTest
32/38 Test #32: StringMessageUTest ....................   Passed    0.02 sec
      Start 33: ActionPlanUTest
33/38 Test #33: ActionPlanUTest .......................   Passed    0.04 sec
      Start 34: ActionTypeUTest
34/38 Test #34: ActionTypeUTest .......................   Passed    0.03 sec
      Start 35: ActionParamTypeUTest
35/38 Test #35: ActionParamTypeUTest ..................   Passed    0.03 sec
      Start 36: AvatarActionUTest
36/38 Test #36: AvatarActionUTest .....................   Passed    0.03 sec
      Start 37: RunningComboProcedureUTest
37/38 Test #37: RunningComboProcedureUTest ............   Passed    0.00 sec
      Start 38: ComboProcedureRepositoryUTest
38/38 Test #38: ComboProcedureRepositoryUTest .........   Passed    0.05 sec

89% tests passed, 4 tests failed out of 38

Total Test time (real) =  80.30 sec

The following tests FAILED:
	 12 - AnaphoraTest (Failed)
	 14 - PLNRulesUTest (Failed)
	 15 - PythonModuleUTest (Failed)
	 19 - RestApiTest (Failed)
Errors while running CTest
make[3]: *** [CMakeFiles/test] 오류 8
make[2]: *** [CMakeFiles/test.dir/all] 오류 2
make[1]: *** [CMakeFiles/test.dir/rule] 오류 2
make: *** [test] 오류 2
```

**Comment by ngeiswei** [comment]
Those tests don't pass on my machine either so I guess I can merge. BTW please just paste the test summary results, like
```
The following tests FAILED:
     12 - AnaphoraTest (Failed)
     14 - PLNRulesUTest (Failed)
     15 - PythonModuleUTest (Failed)
     19 - RestApiTest (Failed)
```
we don't want to bloat the PR message either. Thanks.

**Pull request merged**
