### PR TITLE
Generate lemmas for predicates in R2L

### PR DESCRIPTION
**Pull request by leungmanhin**

### CODE REVIEW

**Comment by leungmanhin** [comment]
Just noticed that some updates to sureal will also be needed to support these lemma predicates, I think it would be better to merge this PR after I've finished updating sureal

**Comment by linas** [comment]
yes.

**Comment by leungmanhin** [comment]
Since R2L should generate those instances anyway, I think this PR is not needed

**Comment by linas** [comment]
specifically, it was pull #2041 that makes these changes un-needed/unwanted.

**Pull request closed without merging**
