### PR TITLE
Type constructor fixes and added truth_value function to Atom

### PR DESCRIPTION
**Pull request by inflector**
Fixed up the Python type constructor macros and mechanism so it uses separate generated files and includes them all from the `type_constructors.pyx` file. 

This should fix the build problem on buildbot: #1518

Also added the a truth_value function to Atom in Python. So you can now do something like:
```
InheritanceLink(
    ConceptNode("Spaceship"),
    ConceptNode("machine")
).truth_value(0.5,0.5)
```

### CODE REVIEW

**Comment by cosmoharrigan** [comment]
Thanks. One thing to consider: What if one wanted to use a different truth value type than the simple truth value?

**Comment by inflector** [comment]
@cosmoharrigan These are not supported in the Python interface at all at the moment. That's how things were all along. I don't know enough about the way the other types are used to fix it yet. 

It may be a bit tricky, but the way that the other truth values are used and differ is only a guess for me at the moment.

**Comment by inflector** [comment]
See: https://github.com/opencog/opencog/blob/master/opencog/cython/opencog/truth_value.pyx#L9

**Comment by cosmoharrigan** [comment]
Oh yeah, that's right.

**Pull request merged**
