### PR TITLE
#3492 Move Satisfier from OpenPsiImplicator so it is possible to release AtomTable

### PR DESCRIPTION
**Pull request by stellarspot**
See the issue #3492 

The idea of the fix is to move the Staisfier from the OpenPsiImplicator class hierarchy and create it only by demand in `check_satisfiability()` method and remove in `imply()` method.

This relies on the methods `check_satisfiability()` and `imply()`  order  execution.
For example if `check_satisfiability()` is called and returns TRUE_TV but `imply()` is not called the AtomTable belonging to `DefaultPatternMatchCB` will not be released and the crash described in #3492 happens again.

### CODE REVIEW

**Comment by vsbogd** [comment]
As `imply()` and `check_satisfiability()` methods share state I don't see good solution without changing scheme API. For instance PR #3496 is a fragile solution which will have different side effects when methods `imply()` and `check_satisfiability()` are called in different order.

Straightforward solution to instantiate `OpenPsiSatisfier` at the beginning of each method and delete it at the end has performance impact obviously. More performant options:
- to pass instance of `OpenPsiSatisfier` to the client with responsibility to delete it;
- to add one method with single callback argument and pass `OpenPsiSatisfier` to this callback thus allowing external user writing any logic in the callback;
Both options require change in API.

**Comment by linas** [comment]
> Straightforward solution to instantiate OpenPsiSatisfier at the beginning of each method and delete it at the end has performance impact obviously

It should have a rather very small performance impact - negligable, I think.  All that Satisfier is doing is allocing a struct, and initializing two or three pointers, and nothing more.   It should be very fast to create and destroy.  Most other code, outside of openpsi, just allocs it on stack (block scope) - that skips the overhead of new/malloc.

**Comment by linas** [comment]
> All that the Satisfier ctor is doing

I mean .. all that the Satisfier ctor is should be doing is something very minimal. I haven't checked recently.  It was originally designed to be very small and efficient; maybe that design went sideways.

**Comment by linas** [comment]
This cannot be merged until the `GhostUTest` and the `OpenPsiImplicatorUTest` both pass.

**Comment by linas** [comment]
Hmm. Now seven different unit tests fail ...

**Comment by stellarspot** [comment]
The problem with the GhostUTest was the following.
There are usually paired calls: OpenPsiImplicator::check_satisfiability(...) and if it passes OpenPsiImplicator::imply(...).

The fix created
* OpenPsiSatisfier in the  OpenPsiImplicator::check_satisfiability(...) and called its check_satisfiability(...) method.
* OpenPsiSatisfier in the  OpenPsiImplicator::imply(...) and called its both check_satisfiability(...) and imply(...) method.

The OpenPsiSatisfier.check_satisfiability(...) first removes the given query from the satisfiability_cache and then uses grounding to find solution.

Usually its fine because between OpenPsiImplicator::check_satisfiability(...)  and OpenPsiImplicator::imply(...) the pattern in question located in AtomSpace.

This is not true for the Ghost rejoinder because after  OpenPsiImplicator::check_satisfiability(...) call it is removed from the AtomSpace so consequent OpenPsiImplicator::imply(...) removes it from the cache and is not able to find it again.

I updated the code to not call OpenPsiSatisfier.check_satisfiability(...)  inside the  OpenPsiImplicator::imply(...) method.

**Comment by stellarspot** [comment]
There are 3 failed tests in [CircleCI](https://circleci.com/gh/opencog/opencog/2107):
```text
The following tests FAILED:
	 17 - AnaphoraTest (OTHER_FAULT)
	 19 - SuRealUTest (Failed)
	 20 - MicroplanningUTest (Failed)
```
SuRealUTest and MicroplanningUTest tests pas on my local system with the current fix.
AnaphoraTest still fails.

**Comment by linas** [comment]
Thanks!  Seems reasonable, merging.

**Pull request merged**
