### PR TITLE
Remove cython handle

### PR DESCRIPTION
**Pull request by inflector**
Updated to work with the atomspace changes removing the Cython Handle object and moving that functionality into Atom.

One change to note is that functions that were returning handles where Handle::INVALID indicated a not found have been changed to return the Python None object instead rather than an Atom object which wrapped an INVALID handle as this is Pythonic.

Also removed a reference to an AtomSpace which was giving an unused variable warning.

### CODE REVIEW

**Comment by inflector** [comment]
The discussion for this pull request is here: https://github.com/opencog/atomspace/pull/604

This request is required to synch up the changes made the above referenced pull request which removes the Cython Handle object from the Cython bindings.

**Comment by inflector** [comment]
NOTE: The circle and jenkins CI are going to fail until the atomspace pull request is integrated and installed.

**Comment by inflector** [comment]
Is there any way to force the checks to run again? These should pass now that the atomspace pull request has been merged.

**Comment by ngeiswei** [comment]
Jenkins, could you retest this please

**Comment by ngeiswei** [comment]
retest this please

**Comment by ngeiswei** [comment]
It would be cool if the Jenkins bot would understand comments such as "Jenkins, could you retest please?"

**Comment by ngeiswei** [comment]
@inflector as for circle-ci you need to log in and push the button "rebuild" in the right upper corner.

**Comment by inflector** [comment]
Ready for merge!

**Comment by wenwei-dev** [comment]
@ngeiswei The Jenkins trigger phrase is a Java regex, the default is "retest this please". I'll set it to "Jenkins, could you retest please?" later.

**Comment by wenwei-dev** [comment]
Jenkins retest this please. 

Sorry, the last failure is caused by a failure of my experimental job. I don't know why it updated the commit status.

**Comment by inflector** [comment]
I have another pull request that needs to be retested once the atomspace merge is finished, and I have a couple of questions:

@wenwei-dev Does "retest this please" work for CircleCI as well? Or just Jenkins?

@ngeiswei I don't seem to have a "rebuild" button after logging into CircleCI, perhaps because I'm not in the list here: https://github.com/orgs/opencog/people?

**Comment by inflector** [comment]
@ngeiswei I'm on the OpenCog project now, but if I go to https://github.com/opencog/opencog/pull/2011 and select "details" for CircleCI, I still get no "build" button. 

I now have OpenCog listed under my organizations in CircleCI, but when I select it, none of the repositories show up below so I can't even create a new project to build OpenCog myself. Something screwy in CircleCI integration.

**Comment by AmeBel** [comment]
- 'retest this please' only works for jenkins
try again now on the cricle-ci rebuild

**Comment by inflector** [comment]
@AmeBel Yay! I now have the "rebuild" button.

**Pull request merged**
