### PR TITLE
Run python tests on  python3

### LINKED ISSUE #3500: Cython tests do not run
Here is the link to the CircleCI run and I can't find there Cython tests: CythonServer and CythonStatistics:
https://circleci.com/gh/opencog/opencog/2024

On my local machine the PYTHONINTERP_FOUND is not set and it is not defined in the opencog project.

### PR DESCRIPTION
**Pull request by AmeBel**
Fixes #3500

### CODE REVIEW

**Comment by AmeBel** [comment]
Merging even though the following tests FAILED:
	 17 - AnaphoraTest (Failed)
	 26 - PythonModuleUTest (SEGFAULT)
	 35 - SurprisingnessUTest (Failed)

**Comment by linas** [comment]
One reason things are failing might be this:
```
-- Setting python RPATH to /usr/local//usr/local/lib/python3/dist-packages/opencog
```

**Comment by linas** [comment]
and I just fixed that ...

**Comment by linas** [comment]
So, is anyone working to fix the unit-test failures that this pull req caused?  If not, maybe we can revert this, until the python agent code gets fixed?

**Comment by vsbogd** [comment]
Why not just ignore tests?

**Comment by linas** [comment]
> Why not just ignore tests?

Sure, but I have gotten into deep, dark and ugly arguments every time I suggest things like this.  I want to purge the abandon-ware in the repo. and the "agents" subsystem is one of them, but various, uhh, external forces think that "agents" are important. But if you create a pull req, I'll merge it :-)

**Pull request merged**
