### PR TITLE
Generate empty types file so cython build works without octomap

### PR DESCRIPTION
**Pull request by ferrouswheel**
Fix for #3513

### CODE REVIEW

**Comment by linas** [comment]
Hmm...  `OpenPsiUTest` now fails with `Failure: ImportError (No module named 'opencog.type_constructors') ... ` and I'm pretty sure that was not failing before this. 

I'm guessing that manually touching the pyx file means that the compile step failed to actually compile the pyx into valid code. (Recall that pyx files are auto-converted to C++ code, and then the C++ code is compiled to create the python bindings, and your change cause the auto-convert-to-C++ step to be skipped.)

Try instead creating an empty `atom_types.script` file, and then triggering it's compile as it normally would (i.e. copy the needed parts of that CMakefile)

**Comment by ferrouswheel** [comment]
#3517 has the same error, and OpenPsiTest fails for me on master even without my change.

**Comment by linas** [comment]
Yeah, but the changes being proposed there are even more broken. Look at some of the the closed pull reqs - (e.g. recent ones in atomspace)  they all have only two failing tests: PythonModules and Anaphora, both failing on missing Agents code (#3500 #3503 and #3509) ... This would be more clear if we had an actual python maintainer to keep that code up-to-date.  We need a python maintainer.

**Comment by ferrouswheel** [comment]
I'm happy to look at those, and the python stuff does look like it needs major tidy up and someone to maintain it. And possibly that could be me in future.

... but that is all a separate issue to this PR.

**Comment by leungmanhin** [comment]
I think the `OpenPsiTest` is a new test that's introduced two days ago when https://github.com/opencog/opencog/pull/3501 got merged?
The usual ones are `OpenPsiRulesUTest`, `OpenPsiImplicatorUTest`, and `OpenPsiSCMUTest` and they all pass.

**Comment by linas** [comment]
Ahh. OK. Based on this, I'm merging. However, if #3501 introduces a new failing unit test, it should not have been merged...

**Pull request merged**
