### PR TITLE
Revert #1889 #1890 #1891

### PR DESCRIPTION
**Pull request by pennachin**
Get master to build again, and when the 3D space map code builds we can redo the merge.

### CODE REVIEW

**Comment by ngeiswei** [comment]
Maybe it's time to have the opencog repo follow the same merging policy as the atomspace repo.

The first step would be to fix (or perhaps disable) the failing unit tests.

**Comment by pennachin** [comment]
We'd been waiting for two things before enabling that policy: someone to fix the anaphora unit test (it's the only failing one left), and @AmeBel to finish his scripts that would work around the need to merge from master whenever a PR falls behind it. 

The requirement that a PR has to be up to date with master is likely going to be more annoying on this repo than on the more focused ones, but I don't know how much work is left to work around it.

**Comment by ngeiswei** [comment]
Actually I don't know if @AmeBel script is necessary. With github "Update" button merging the master to a PR is really easy.

**Comment by AmeBel** [comment]
@ngeiswei yes it easy, but cumbersome when there are multiple prs.

**Comment by ngeiswei** [comment]
I agree, it's useful to have that script. I just want to say that it's not absolutely necessary, the current policy is already manageable.

**Comment by pennachin** [comment]
I'm happy to discuss this on the mailing list, and I'd be really happy if someone could fix the anaphora test soon. I'm also OK with disabling it, since no one seems to use the anaphora code at the moment, and it would be nice to have some green builds on this repo...

**Comment by linas** [comment]
What's the problem? It builds, the unit tests pass, on my machine and on that travis-ci thingy.

**Comment by linas** [comment]
p.s. I absolutely despise the travis-CI thingy. I very strongly believe it is a really bad concept. The thing to discuss is turning it off, not turning it on in yet more places.

**Comment by linas** [comment]
Look, this merged introduce SIX new unit tests that did not exist before:
```
SpaceServerUTest
OctomapOcTreeUTest
SpaceMapUtilUTest
EntityRecorderUTest
CythonSpatial
CythonSpacetime
```
Of these SIX new tests, FOUR passed, and TWO failed: OctomapOcTreeUTest  and CythonSpatial . Of the previous 30 tests, there was no change in status; the same two fail, like always (AnaphoraTest, CythonMoses) -- just as they did before this merge.  

Thus, this merge does NOT regress any existing unit tests. It adds new features, and it adds new tests.  But, instead of being aware of this, the CircleCI thing once again falls flat on its face.  It is not hard to figure out what changed or to track it, but does CircleCI do that? No, it doesn't.  What use is it? Why are we using it? The whole process and methodology is stunningly stupid and brain-dead.

**Comment by ngeiswei** [comment]
@linas are you saying that it can be useful to have failing tests in the master? I mean why not, I'm genuinely asking.

Having CircleCI perform bisection to discover the failing commit is an excellent suggestion. @AmeBel do you think that would be possible to script that? I know git already offers some plugin tool just for that. The github interface is certainly amenable to it.

I agree the current methodology can be improved. But I disagree that it is useless. I have pushed PRs on the opencog repo that broke other parts (detected by utests) more than once, this would not have happened on the atomspace repo.

**Comment by pennachin** [comment]
Those PR flat out don't build on CircleCI, I don't know where you got the opposite impression. If they build on your machine, then it should be straightforward to get them to build on a fresh install, but that should happen before merging onto master, not after.

I'm happy to have a discussion on the methodology on the mailing list, Linas. If we can focus on what is actually wrong, and how to fix it, we can probably make progress. Just cursing the methodology is unlikely to be productive.

**Comment by rTreutlein** [comment]
The issue with them no building is that the 3DSpaceMap code now depends on ROS which is not installed in the Image the CricleCI uses. 
I am currently adding all the new dependencies to the cmake files.

And i would be for using the same merge policy as in atomspace.

**Comment by AmeBel** [comment]
@ngeiswei please point me to the plugins you mentioned.

**Comment by pennachin** [comment]
Thanks, @rTreutlein -- Linas probably has ROS available on his environment, which explains why it would build on his machine.

**Comment by ngeiswei** [comment]
@AmeBel actually it seems to be integrated to git, just type `man git bisect` for more info.

**Comment by linas** [comment]
To be crystal clear: the current integration process is fundamentally broken. I blame the horrifically mis-designed Circle-CI for half of it.  We cannot continue working like this, pulling stunts like this is a violation of cultural norms.  This is not the correct way to develop software.

**Comment by linas** [comment]
Sorry. I'm just in a bad mood.

**Pull request merged**
