### PR TITLE
Update cython attention bank wrapper

### PR DESCRIPTION
**Pull request by stellarspot**
- Move cython attention bank wrapper to cython/opencog directory
- Update get_atoms_by_av method in bank.pyx
- Add get/set sti, vti, lti, vlti methods to AttentionBank cythonc class
- Update AttentionBankTest

### CODE REVIEW

**Comment by stellarspot** [comment]
The following [tests](https://circleci.com/gh/opencog/opencog/2127) fail:
```
The following tests FAILED:
	 18 - SuRealUTest (Failed)
	 19 - MicroplanningUTest (Failed)
```

**Comment by linas** [comment]
> Move cython attention bank wrapper to cython/opencog directory

Would it be possible to not do this?  There is a long-term plan to split up the contents of this repo into half-a-dozen stand-alone repos, each having a well-define function and API. One of those components would be the attention-bank and everything that goes along with it.  Thus, the cython code should stay with it, to make that movement easier.  See  issue #3391

**Comment by stellarspot** [comment]
I Moved the bank.pyx and bank.pxd back to opencog/attentionbank/cython/opencog directory.

**Comment by stellarspot** [comment]
The [failed](https://circleci.com/gh/opencog/opencog/2129) tests:
```
The following tests FAILED:
	 19 - SuRealUTest (Failed)
	 20 - MicroplanningUTest (Failed)
```

**Comment by linas** [comment]
Thank you!

**Comment by linas** [comment]
BTW, feel free to re-arrange code between the attention-bank and the other attention directory. 

Feel free to split this out into it';s own git repo :-)

While walking around yesterday, I realized that, for one of my experiments, I would like to have something a lot like the attentionbank, but maybe with different features, different functions different capabilites. Or maybe not. NOt yet sure.  So if you get any bright ideas to improve, enhance, make-better, add new features to attention or attentionbank, please do so. Now is a good time for that.

**Comment by linas** [comment]
On thing I think that I want or need is a recording of everything that was in attentionbank, in historical order.  A kind-of chain or mesh of all the atoms that got visited.    Also -- keeping such a chain might make attentiion-decay simpler/easier.  I don't know. Again, until I run my experiments, I won't know, and that won't happen for half-a-year, at least.

**Pull request merged**
