### PR TITLE
new commits -- thought the old ones were resolved, drat it!

### PR DESCRIPTION
**Pull request by anitzkin**
I thought that the previous mess had been resolved this morning before I added these commits. Sorry.

### CODE REVIEW

**Comment by anitzkin** [comment]
So it is now everything in the last 3 commits that we want to keep.  These three were made on a different branch than the others. Don't know why they're being appended to the earlier ones.

**Comment by linas** [comment]
please stop doing this

**Comment by linas** [comment]
aaron, your code has been checked in.  Get someone over there to show you how to set your git branch to master, to get pull, and then how to create a new branch for you to work in.  If there are problems with what is curretnly, you should work to resolve those problems, instead of continuing to pile on with the mistakes and errors.

**Comment by anitzkin** [comment]
Linas, I do all that.  I committed my new work because I thought the
previous commits had been cherry picked and resolved.

**Pull request closed without merging**
