### PR TITLE
add r2l documentation from Aaron

### PR DESCRIPTION
**Pull request by AmeBel**
This entry is an edit for word document received by me
from Aaron Nitzkin(https://github.com/anitzkin) on
on July 10th 2015. I have made a style edit to fit 
markdown.

### CODE REVIEW

**Comment by AmeBel** [comment]
@anitzkin thanks :smile:

**Comment by williampma** [comment]
Some of the "put in bold" is not in bold.

**Comment by AmeBel** [comment]
I don't know why the rendering on github is not working. My IDE makes a perfect render as per github's flavor of markdown.

**Comment by anitzkin** [comment]
I had to write it in Apache OpenOffice because I didn't have Word on my
laptop; I know it does some strange things
with the translation from .odt to .doc, but I couldn't see what it does,
since I don't have Word on this laptop . . . hope
you can recover the intended formatting :-)

**Comment by AmeBel** [comment]
Did my best https://github.com/opencog/opencog/blob/master/opencog/nlp/relex2logic/README.md

**Comment by bgoertzel** [comment]
Thanks Aaron and Amen, this should be useful to whomever refactors R2L
(probably Rui Ting...)

On Mon, Jul 13, 2015 at 6:22 AM, Amen Belayneh <notifications@github.com>
wrote:

> Did my best
> https://github.com/opencog/opencog/blob/master/opencog/nlp/relex2logic/README.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/pull/1676#issuecomment-120885496>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Pull request merged**
