### PR TITLE
Cleanup guile module usage.

### PR DESCRIPTION
**Pull request by linas**

### CODE REVIEW

**Comment by linas** [comment]
this requires merging https://github.com/opencog/atomspace/pull/703 as a pre-requisite

**Comment by linas** [comment]
opencog/atomspace#703  has been merged.

**Comment by linas** [comment]
test this please

**Comment by linas** [comment]
test this please

**Comment by linas** [comment]
test this please

**Comment by linas** [comment]
test this please

**Comment by linas** [comment]
test this please

**Comment by linas** [comment]
test this please

**Comment by linas** [comment]
Guys, this circle-jenkins-cii is just totall bullshit and a major impediment to rational, productive development.   I can't tell you how much this shit sucks dick sucks balls. The ENTIRE FUCKING CONCEEPT OF CI AND HOW IT IS IMPLEMENTED IS DEEPLY AND FUNDA-FUCKING-MENTALLY FLAWED.

I DON'T KNOW HOW MANY TIMES I HAVE TO SCREAM IN PAIN.

YOU ASSHOLE WHO DON'T ACTAULLY WRITE ANY CODE JUST COME ON DOWN FROM THE HIGH MOUNTAINS AND IMPOSE THESE BULLSHIT SYSTEMS DESIGNED TO FUCK OVER CODERS AND LOWER PRODUCTIVY

DEN, IF YOU WANT TO GO HAVE A NICE OPENCOD DEMO SO THAT YOU CAN RAISE CAPITAL FOR OPENCOG, THEN TURN OFF THIS BULLSHIT SYSTEM.

i HAVE LOST 4 WEEKS OUT OF THE LAST SIX MONTHS SCREWING WITH THIS BULLSHIT SYSTEM.  STOP RUINING MY PRODUCTIVITY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by bgoertzel** [comment]
Woops ...

linas, i am truly sorry these experiments with CI have been so frustrating
for you ...  I really do not like causing people distress, especially
fellow AI geeks ...

I am in the middle of a quant finance conference just now and will discuss
with amen and wenwei later today...

Ben

**Pull request merged**
