### PR TITLE
Reasoning: Minor shuffling

### PR DESCRIPTION
**Pull request by williampma**
RuleUTest still passes so I think these changes are OK.

For #1367

### CODE REVIEW

**Comment by AmeBel** [comment]
@misgeatgit  how do one define a custom control policy, for eg for r2l?

**Comment by misgeatgit** [comment]
If you are referring to the policy configuration file, you can add another policy config file or to that extent you can create a Rule Object on the fly without the need to load a config file. And if you are referring to the runtime control, there is an interface https://github.com/opencog/opencog/blob/master/opencog/reasoning/RuleEngine/rule-engine-src/pln/ForwardChainerCallBack.h that you can implement and pass to the  do_chain method(https://github.com/opencog/opencog/blob/master/opencog/reasoning/RuleEngine/rule-engine-src/pln/ForwardChainer.h#L55).

**Comment by AmeBel** [comment]
how are multiple control-policies handled? Is there a means of specifying which control policy to use by cog-fc?

**Comment by williampma** [comment]
Not currently as far as I can tell.  Something need to be done to get rid of the hard-coded default_cpolicy.json path.

**Comment by bgoertzel** [comment]
Specifying the control policy via cog-fc or cog-bc would seem a good
feature to have...

On Mon, Mar 9, 2015 at 5:43 PM, William Ma <notifications@github.com> wrote:

> Not currently as far as I can tell. Something need to be done to get rid
> of the hard-coded default_cpolicy.json path.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/pull/1377#issuecomment-77824252>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by misgeatgit** [comment]
The constructor accepts another  conf file https://github.com/opencog/opencog/blob/master/opencog/reasoning/RuleEngine/rule-engine-src/pln/ForwardChainer.h#L53. But there is a lot of space for improvement as its mentioned.

**Comment by AmeBel** [comment]
by the, why was it decided to have the control-policy outside the atomspace?

**Comment by bgoertzel** [comment]
The control policy is a customized callback to the Pattern Matcher.   It
has to be plugged into the Pattern Matcher C++ code, so it can't be
implemented in the Atomspace.   Implementing the Pattern Matcher in the
Atomspace would be way too slow at this stage, I'm afraid...

On Mon, Mar 9, 2015 at 5:56 PM, Amen Belayneh <notifications@github.com>
wrote:

> by the, why was it decided to have the control-policy outside the
> atomspace?
>
> On Mon, Mar 9, 2015 at 5:48 PM Misgana Bayetta <notifications@github.com>
> wrote:
>
> > The constructor accepts another conf file
> >
> https://github.com/opencog/opencog/blob/master/opencog/reasoning/RuleEngine/rule-engine-src/pln/ForwardChainer.h#L53
> .
> > But there is a lot of space for improvement as its mentioned.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/opencog/opencog/pull/1377#issuecomment-77824962>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/pull/1377#issuecomment-77825964>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by williampma** [comment]
@misgeatgit  Can you review this?  It's your code :)

If everything is OK, someone can merge.

**Comment by misgeatgit** [comment]
@williampma I agree with the changes. Someone with merge privilege should merge it.

**Comment by linas** [comment]
@AmeBel has permissions, right?

**Comment by AmeBel** [comment]
yes i do, but i don't touch anything c++ yet :-) Maybe William/Misgana
should get a write access.

**Comment by williampma** [comment]
Weird, buildbot is hanging up on a completely unrelated test after this change... no idea why...

**Pull request merged**
