### PR TITLE
Make a python binding of statistics library

### PR DESCRIPTION
**Pull request by kim135797531**
* DataProvider class: ```PyDataProvider```
* Probability class: ```PyProbability```
* Entropy class: ```PyEntropy```
* InteractionInformation class: ```PyInteractionInformation```
* Unit test 'CythonStatistics'

This classes wrap the C++ statistics library classes, but support only for python long type statistic, since cython binding doesn't support the **declaration of template class** now.

In this reason, python binding provides interface to calculate statistic of Atom.
* ```PyDataProviderAtom, PyProbabilityAtom, PyEntropyAtom, PyInteractionInformationAtom```

Result of unit test:
```
The following tests FAILED:
	 12 - AnaphoraTest (Failed)
	 14 - PLNRulesUTest (Failed)
	 15 - PythonModuleUTest (Failed)
	 20 - RestApiTest (Failed)
```

### CODE REVIEW

**Comment by ngeiswei** [comment]
It looks good but I'm not confident enough about Python binding to merge that.

**Comment by linas** [comment]
Why are we even trying to do this? The C++ code in learning/statistics is weak and not very interesting; (it cannot be used in any sort of general fashion; its idiosyncratic and applicable to very narrow use cases) and so I can't imagine why we would want to take weak code, and add python bindings to it.  Surely SciPy or some other toolkit already has much more general and powerful code for these kinds of things?

**Comment by bgoertzel** [comment]
I don't think SciPy or other standard toolkits contain code for calculating
the interaction information...

On Tue, Aug 4, 2015 at 6:01 PM, Linas Vepštas <notifications@github.com>
wrote:

> Why are we even trying to do this? The C++ code in learning/statistics is
> weak and not very interesting; (it cannot be used in any sort of general
> fashion; its idiosyncratic and applicable to very narrow use cases) and so
> I can't imagine why we would want to take weak code, and add python
> bindings to it. Surely SciPy or some other toolkit already has much more
> general and powerful code for these kinds of things?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/pull/1699#issuecomment-127659226>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by linas** [comment]
http://scikit-learn.org/stable/modules/generated/sklearn.metrics.mutual_info_score.html

**Comment by bgoertzel** [comment]
Linas, that code is just for binary  mutual information, not n-ary
interaction information,

https://en.wikipedia.org/wiki/Interaction_information

On Tue, Aug 4, 2015 at 7:32 PM, Linas Vepštas <notifications@github.com>
wrote:

>
> http://scikit-learn.org/stable/modules/generated/sklearn.metrics.mutual_info_score.html
>
> On Tue, Aug 4, 2015 at 12:27 PM, bgoertzel <notifications@github.com>
> wrote:
>
> > I don't think SciPy or other standard toolkits contain code for
> calculating
> > the interaction information...
> >
> > On Tue, Aug 4, 2015 at 6:01 PM, Linas Vepštas <notifications@github.com>
> > wrote:
> >
> > > Why are we even trying to do this? The C++ code in learning/statistics
> is
> > > weak and not very interesting; (it cannot be used in any sort of
> general
> > > fashion; its idiosyncratic and applicable to very narrow use cases) and
> > so
> > > I can't imagine why we would want to take weak code, and add python
> > > bindings to it. Surely SciPy or some other toolkit already has much
> more
> > > general and powerful code for these kinds of things?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/opencog/opencog/pull/1699#issuecomment-127659226>.
> > >
> >
> >
> >
> > --
> > Ben Goertzel, PhD
> > http://goertzel.org
> >
> > "The reasonable man adapts himself to the world: the unreasonable one
> > persists in trying to adapt the world to himself. Therefore all progress
> > depends on the unreasonable man." -- George Bernard Shaw
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/opencog/opencog/pull/1699#issuecomment-127685180>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/pull/1699#issuecomment-127686314>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by keyvan-m-sadeghi** [comment]
cffi might help here, I created a separate issue #1700

**Comment by kim135797531** [comment]
Linas, I totally agree with your opinion. When I was planning my project, C++ interaction information algorithm seems to be frequently used by others, because it was implemented by template class. However I discovered that the library was not used in any other component when making them to work.

Though the above situation, I finished making algorithm to work in C++ and Python but that implementation(particularly in Python binding) looking not very clean. I didn't know about SciPy library, but now I want to use them because it will be much more efficient.
As Ben said, SciPy doesn't have n-ary algorithm. But if we decide to delete the current statistic library in C++, it can be made by combining the SciPy binary algorithms, right?

Or if we keep our structure, using the cffi(recommended by Keyvan) would be cleaner way than current. But I worry that cffi might be make many new issues when trying to import them.

Anyway, I want to use my python binding for the moment because my project has only two weeks left until the GSoC period is over.

**Comment by misgeatgit** [comment]
@kim135797531 's GSOC project entirely depends on this PR. @linas  would you mind merging it so that @kim135797531 could proceed and finish his GSOC project?

**Comment by linas** [comment]
OK. Whatever. My general impression of the C++ code was that is was wildly over-engineered, excessively complexticated, clunky and hard to use.  These are simple concepts, I don't understand why the code to implement them is so complex.  So I kind-of don't like the whole approach. 

The C++ code consists of 700 LOC. The python bindings add another 600 LOC.  By contrast, equivalent code that does this for specific natural language patterns in the atomspace can be found in opencog/nlp/learn/compute-mi.scm and it is maybe 1/10th the total size.   So what is all that complex C++ code actually doing? 

In particular, I don't see any way of specifying which atoms the probabilities are to be computer for, or which atom patterns the interaction information is being computed for.  There's no atomspace-anything in that code ... wtf??  How are you even going to find those atoms?  yes, maybe the pattern matcher, to find all of the atoms for which the interaction information is being computed, would be great.  But neither the C++ code nor the python bindings point you at the atomspace to use, or tell you which atoms to sum up. So,yeah my reaction is still WTF??

**Comment by linas** [comment]
So, i my mind, the RIGHT way to compute probabilities and interaction information, using the pattern matcher to find all the relevant atoms, would be to take the function `compute-pair-wildcard-counts-pm` here: https://github.com/opencog/opencog/blob/master/opencog/nlp/learn/compute-mi.scm#L466  and replace all the word-pair specific code by generic code  for whichever hypergraphs you are interested in. 

So: lines 470-490 specify the left side of a word pair: this is replaced by some user-specified pattern.  Lines 494-515 specify the right side.  The partial sums for the interaction information is computed in lines 516-558 (just 40 lines of code total!! including database access!) 

So take that code, rip out the word-pair specific stuff, keep the database access code, allow the user to specify the patterns over which the interaction information is being computed ... that would actually be useful.  Re-write it in C++ or python, for all I care.

**Comment by bgoertzel** [comment]
FYI, Shujing says she has other code for calculating interaction
information in the context of the pattern miner....   It's somewhat
specialized to the pattern miner, she says, but should probably be looked
at  too if someone is going to write different/better code for interaction
information calculation in the Atomspace...

ben

On Thu, Aug 20, 2015 at 3:32 AM, Linas Vepštas <notifications@github.com>
wrote:

> So, i my mind, the RIGHT way to compute probabilities and interaction
> information, using the pattern matcher to find all the relevant atoms,
> would be to take the function compute-pair-wildcard-counts-pm here:
> https://github.com/opencog/opencog/blob/master/opencog/nlp/learn/compute-mi.scm#L466
> and replace all the word-pair specific code by generic code for whichever
> hypergraphs you are interested in.
>
> So: lines 470-490 specify the left side of a word pair: this is replaced
> by some user-specified pattern. Lines 494-515 specify the right side. The
> partial sums for the interaction information is computed in lines 516-558
> (just 40 lines of code total!! including database access!)
>
> So take that code, rip out the word-pair specific stuff, keep the database
> access code, allow the user to specify the patterns over which the
> interaction information is being computed ... that would actually be
> useful. Re-write it in C++ or python, for all I care.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/pull/1699#issuecomment-132752719>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by kim135797531** [comment]
So this is my overall impression of the C++ code:

**Useful:**
- The C++ code can evaluate the n-gram interaction information.
--> +50 line

**Useful or Over-Engineered:**
- The C++ code can handle any sort of data set, not only for data in atomspace. So the reason why we can't find any code related with atomspace is using the C++ template class: users can initialize the class with Link, or Atom, or int(type), or any others. The C++ code was split between the managing data part and calculating algorithm part.
--> +200 line
- Also the user can manually increase the appearance value of data, not only for the number of atom in atomspace.
--> +100 line

**Over-Engineered:**
- For Python, we have to make headers about all of above things but currently Cython doesn't support the template class code.
--> +Almost all of Python code
- The user can calculate only for probability, only for entropy, or only for interaction information.
--> +100 line
- Divided class file
--> +100 line

So the algorithm related with statistic in the C++ code is only 50~100 lines, but managing the custom data structure + template class + spliting class makes bulky code. If we limit the area of library only for atoms and merge code into one file, then it would be similar to `compute-mi.scm`.

...And if I had known about this scheme code, I would use them for my project. Expanding this code to calculate n-gram information would be easier than C++..

**Pull request merged**
