### PR TITLE
Fix for bug #2328

### PR DESCRIPTION
**Pull request by linas**
I believe that this should fix bug #2328, although I have not finished testing.

The core issue was this: shell was being destroyed (because netcat closed the socket) even before evaluation of the expression that was sent even started.  As a result, initialization is skipped (the shell destructor tears down the virtual function vtable; initialization was being done in c++ virtual functions).  The initialization set the atomspace; without that, the atomspace is null, leading to a crash.

### CODE REVIEW

**Comment by ngeiswei** [comment]
It works for me (15m so far, all components activated, never happened before)!

Respect, man!!! :-)

**Comment by ngeiswei** [comment]
Shit, I think I spoke too fast. I did experienced a crash, unfortunately the core dump is empty, but based on the message display right before the crash I think it probably corresponds to trace https://github.com/opencog/opencog/issues/2328#issuecomment-236268872

Anyway, it's still a very big improvements, probably enough to let me (and hopefully others) focusing on demoing.

**Comment by ngeiswei** [comment]
Yep, re-stumbled on it, I confirm the bt is https://github.com/opencog/opencog/issues/2328#issuecomment-236268872 however it might triggered by my own demo branch. Still trying to figure that out.

**Comment by linas** [comment]
when I was debugging and fixing, I never saw that particular stack trace
(in the unprotect_object code)  I'll try some fancier test cases, and see
what happens.

--linas

**Pull request merged**
