### PR TITLE
merge minecraft 3D spacemap

### PR DESCRIPTION
**Pull request by linas**
This is a merge of the 3D spacemap code in  opencog/opencog-to-minecraft to here, where it belongs...

### CODE REVIEW

**Comment by linas** [comment]
oh there already was a 3D spacemap branch ... I forgot

**Comment by linas** [comment]
Re-open, it seems like this has newer code.

**Comment by linas** [comment]
see also the discussion here: https://github.com/opencog/opencog-to-minecraft/pull/1

**Comment by rTreutlein** [comment]
@linas this can be closed now, right?

**Comment by linas** [comment]
yes

**Pull request closed without merging**
