### PR TITLE
R2l tmp

### PR DESCRIPTION
**Pull request by rodsol**
Passing the lemma instead of the original word string to the helpers

### CODE REVIEW

**Comment by AmeBel** [comment]
Why pass the lemma string? Has there been to get rid of partial-abstractions of concepts?

**Comment by williampma** [comment]
R2L has always passed Lemma to the rule-helpers.  This is just to fix the incorrect argument passed in from the URE version.

**Comment by AmeBel** [comment]
yes it has, but that is b/c it called `get-instance-name` which returned word-instance-str.

**Comment by williampma** [comment]
Hummm... not sure that's true.  For "He ate an apple.":
```
; ##### START OF R2L #####
(SVO-rule "he" (get-instance-name "he" "he@30ce5064-18cc-4d98-bcff-c47697846bb5" (ParseNode "sentence@aa8b3678-0026-42a9-954a-9dffd344ae85_parse_0")) "eat" (get-instance-name "eat" "ate@4863cc57-ff99-416f-b04f-107007fd1b66" (ParseNode "sentence@aa8b3678-0026-42a9-954a-9dffd344ae85_parse_0")) "apple" (get-instance-name "apple" "apple@dced296b-dd60-4efc-b6b9-0ec1c457376a" (ParseNode "sentence@aa8b3678-0026-42a9-954a-9dffd344ae85_parse_0")))
(tense-rule "eat" (get-instance-name "eat" "ate@4863cc57-ff99-416f-b04f-107007fd1b66" (ParseNode "sentence@aa8b3678-0026-42a9-954a-9dffd344ae85_parse_0")) "past")
(declarative-rule (InterpretationNode "sentence@aa8b3678-0026-42a9-954a-9dffd344ae85_parse_0_interpretation_$X"))
(definite-rule "he" (get-instance-name "he" "he@30ce5064-18cc-4d98-bcff-c47697846bb5" (ParseNode "sentence@aa8b3678-0026-42a9-954a-9dffd344ae85_parse_0")))
(r2l-marker-processing)

; ##### END OF A PARSE #####
```
The SVO-rule is passed "eat" instead of "ate", so it's passing the lemma.

**Comment by AmeBel** [comment]
but what is returned?

**Comment by williampma** [comment]
```
      (ImplicationLink
         (PredicateNode "ate@c16c61c0-27e1-4326-8e05-6424f2cd0757")
         (PredicateNode "eat" (ptv 1 0 1))
      )
```

The only place that uses the non-instanced word.

**Comment by AmeBel** [comment]
never mind got it.

**Pull request merged**
