### PR TITLE
add function in xpatternminer unit test

### PR DESCRIPTION
**Pull request by Bitseat**
@ngeiswei Here is the function and the files I added.

### CODE REVIEW

**Comment by linas** [comment]
Unit tests should not depend on immense datasets.  Large datasets can be tested with system tests; unfortunately, right now, we do not have any policy for system tests, or any repository in which they could be placed.   A discussion and resolution is needed on the mailing list.

Please do not merge this, until the datasets are cut down to several hundred lines of code at most.

**Comment by linas** [comment]
Also, given that this is testing lojban, it would be better to create a brand-new, stand-alone `LojbanUTest` instead of shoe-horning this into an existing unit test.

**Comment by ngeiswei** [comment]
Agreed. Though I don't mind too much having this test inserted in `XPatternMinerUTest.cxxtest` since it's only purpose is to test the pattern miner, independently of how the lojban parser works. Moving it to a standalone `LojbanUTest` would certainly be justified if the unit test relied on calling the lojban parser though.

**Comment by linas** [comment]
Replaced by #3019

**Pull request closed without merging**
