### PR TITLE
Conceptual Blending with Interaction Information theory

### PR DESCRIPTION
**Pull request by kim135797531**
A blender can choose the link set which has largest value of interaction information.

## Algorithm Step
1. Blender finds the conflict links with given threshold(difference of confidence, ...).
2. Make a pool of target links.
  * Target links are every link located in related nodes.
  * Related node is node that has InheritanceLink with source node of blend.
3. Calculate the probabilities from pool of target links.
4. Make the 2^k available conflict link cases if there exists k conflicts.
5. Calculate the interaction information for each available conflict link cases.
6. Choose links have largest value, and connect to new blend.

#### Input
```
- Typical 'bat'
  -> eat flies
  -> has claws
  -> has sonar
  -> live in cave
  -> subclass of 'winged'
  -> subclass of 'nocturnal'
```
```
- Typical 'man'
  -> eat steak
  -> subclass of 'two-legged'
  -> subclass of 'fingered'
```
```
- Subset of 'bat'
  -> funnel_eared, megabat, vesper,
  -> night_stalker(Eats steak),
  -> Zubat(Pokemon)
- Subset of 'man'
  -> scientist, police, programmer,
  -> ancients(Lives in cave),
  -> vegetarian(Don't eats steak)
```
#### Output
[Original Example](https://github.com/kim135797531/opencog/blob/blending-interaction-information/examples/python/conceptual_blending/4_blend_with_interaction_information.py)
Link set that has largest interaction information value:
```
sonar, nocturnal, winged, fingered, cave, steak, claws, flies, two-legged,
: 1.11336374283
```
For example, an entity that has links:
```
sonar, winged, fingered, steak, claws, flies, two-legged,
: 1.0826215744
-> (eat steak)
-> (eat flies) AND (has sonar) AND (has claws) 
-> (winged) AND (fingered) AND (two-legged)
```
is more surprising than the entity that has:
```
sonar, winged, fingered, cave, claws, flies, two-legged,
: 1.07536005974
-> (live_in cave)
-> (eat flies) AND (has sonar) AND (has claws)
-> (winged) AND (fingered) AND (two-legged)
```

## Limits
* First, blender thinks that links are conflicted if only two links are exactly same attribute except TruthValue.

So this case is conflict:
```
InheritanceLink(bat two-legged)<0>,
InheritanceLink(man two-legged)<1>
```
but this case is non(but unveiled) conflict.
```
InheritanceLink(bat flies)<1>,
InheritanceLink(man two-legged)<1>
```
Find the unveiled conflicts via PLN would be great for this case.

* Second, Interaction Information algorithm takes very long time if we not give any limit.
  * Actually `O(n*(2^k))` if there exists n related nodes and k target links.
  * Since the time complexity of an algorithm, we can limit the max n-gram to evaluate the interaction information. See [Conceptual Blending Config Format](https://github.com/kim135797531/opencog/blob/blending-interaction-information/opencog/python/blending/blend-config-format.md).

## Bulid Log
```
The following tests FAILED:
	 11 - AnaphoraTest (Failed)
	 13 - PLNRulesUTest (Failed)
	 14 - PythonModuleUTest (Failed)
	 19 - RestApiTest (OTHER_FAULT)
```

## Note
* This pull request is for adding interaction information theory in blender. But the commit( d930fe00fd7734f98796c66fd0ae813c577d6327 ) has a plenty of changes due to written detailed comments in overall files.

### CODE REVIEW

**Comment by bgoertzel** [comment]
!!!!

Very cool ;-)

Yes, it's just a simplistic "toy" example -- but it's really cool to see
this simplistic example really working ;) ...

You are right that to do this really intelligently, PLN would need to be
invoked to find hidden conflicts -- and in general to more accurately
estimate interaction information based on indirectly given information that
is still resident in the Atomspace....   But what you've done is a
foundation that the PLN-enabled version can be built on, as a
straightforward extension...

(Nil may have code comments, I'm just responding to the cool demo and
general comments and I have only glanced at the code...)

-- Ben

On Sat, Aug 22, 2015 at 3:16 PM, DongMin Kim <notifications@github.com>
wrote:

> A blender can choose the link set which has largest value of interaction
> information.
> Algorithm Step
>
>    1. Blender finds the conflict links with given threshold(difference of
>    confidence, ...).
>    2. Make a pool of target links.
>       - Target links are every link located in related nodes.
>       - Related node is node that has InheritanceLink with source node of
>       blend.
>    3. Calculate the probabilities from pool of target links.
>    4. Make the 2^k available conflict link cases if there exists k
>    conflicts.
>    5. Calculate the interaction information for each available conflict
>    link cases.
>    6. Choose links have largest value, and connect to new blend.
>
> Result Example Input
>
> - Typical 'bat'
>   -> eat flies
>   -> has claws
>   -> has sonar
>   -> live in cave
>   -> subclass of 'winged'
>   -> subclass of 'nocturnal'
>
> - Typical 'man'
>   -> eat steak
>   -> subclass of 'two-legged'
>   -> subclass of 'fingered'
>
> - Subset of 'bat'
>   -> funnel_eared, megabat, vesper,
>   -> night_stalker(Eats steak),
>   -> Zubat(Pokemon)
> - Subset of 'man'
>   -> scientist, police, programmer,
>   -> ancients(Lives in cave),
>   -> vegetarian(Don't eats steak)
>
> Output
>
> Original Example
> <https://github.com/kim135797531/opencog/blob/blending-interaction-information/examples/python/conceptual_blending/4_blend_with_interaction_information.py>
> Link set that has largest interaction information value:
>
> sonar, nocturnal, winged, fingered, cave, steak, claws, flies, two-legged,
> : 1.11336374283
>
> For example, an entity that has links:
>
> sonar, winged, fingered, steak, claws, flies, two-legged,
> : 1.0826215744
> -> (eat steak)
> -> (eat flies) AND (has sonar) AND (has claws)
> -> (winged) AND (fingered) AND (two-legged)
>
> is more surprising than the entity that has:
>
> sonar, winged, fingered, cave, claws, flies, two-legged,
> : 1.07536005974
> -> (live_in cave)
> -> (eat flies) AND (has sonar) AND (has claws)
> -> (winged) AND (fingered) AND (two-legged)
>
> Limits
>
>    - First, blender thinks that links are conflicted if only two links
>    are exactly same attribute except TruthValue.
>
> So this case is conflict:
>
> InheritanceLink(bat two-legged)<0>,
> InheritanceLink(man two-legged)<1>
>
> but this case is non(but unveiled) conflict.
>
> InheritanceLink(bat flies)<1>,
> InheritanceLink(man two-legged)<1>
>
> Find the unveiled conflicts via PLN would be great for this case.
>
>    - Second, Interaction Information algorithm takes very long time if we
>    not give any limit.
>       - Actually O(n*(2^k)) if there exists n related nodes and k target
>       links.
>       - Since the time complexity of an algorithm, we can limit the max
>       n-gram to evaluate the interaction information. See Conceptual
>       Blending Config Format
>       <https://github.com/kim135797531/opencog/blob/blending-interaction-information/opencog/python/blending/blend-config-format.md>
>       .
>
> Bulid Log
>
> The following tests FAILED:
>      11 - AnaphoraTest (Failed)
>      13 - PLNRulesUTest (Failed)
>      14 - PythonModuleUTest (Failed)
>      19 - RestApiTest (OTHER_FAULT)
>
> Note
>
>    - This pull request is for adding interaction information theory in
>    blender. But the commit( d930fe0
>    <https://github.com/opencog/opencog/commit/d930fe00fd7734f98796c66fd0ae813c577d6327>
>    ) has a plenty of changes due to written detailed comments in overall files.
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/opencog/opencog/pull/1736
> Commit Summary
>
>    - Make StatisticData to save large count
>    - Add an explanation in example 3
>    - Make a n_gram limit option in InteractionInformation
>    - Delete obsolete link in blend config
>    - Move duplicate code to connect_util.py
>    - Apply an interaction information theory to blender
>    - Add a dump of output in each example
>    - Make an unit test of interaction information algorithm
>    - Expand the source links of interaction information
>    - Write a detailed comments in blending project
>
> File Changes
>
>    - *M* examples/python/conceptual_blending/1_blend_simple.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-0> (10)
>    - *M* examples/python/conceptual_blending/2_blend_with_config.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-1> (13)
>    - *M*
>    examples/python/conceptual_blending/3_blend_with_conflict_links.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-2> (42)
>    - *A*
>    examples/python/conceptual_blending/4_blend_with_interaction_information.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-3> (294)
>    - *M* examples/python/conceptual_blending/README.md
>    <https://github.com/opencog/opencog/pull/1736/files#diff-4> (4)
>    - *M* opencog/cython/opencog/statistics.pxd
>    <https://github.com/opencog/opencog/pull/1736/files#diff-5> (14)
>    - *M* opencog/cython/opencog/statistics.pyx
>    <https://github.com/opencog/opencog/pull/1736/files#diff-6> (19)
>    - *M* opencog/learning/statistics/DataProvider.h
>    <https://github.com/opencog/opencog/pull/1736/files#diff-7> (24)
>    - *M* opencog/learning/statistics/InteractionInformation.h
>    <https://github.com/opencog/opencog/pull/1736/files#diff-8> (31)
>    - *M* opencog/learning/statistics/Probability.h
>    <https://github.com/opencog/opencog/pull/1736/files#diff-9> (4)
>    - *M* opencog/python/blending/blend-config-format.md
>    <https://github.com/opencog/opencog/pull/1736/files#diff-10> (13)
>    - *M* opencog/python/blending/blend.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-11> (20)
>    - *M* opencog/python/blending/src/chooser/README.md
>    <https://github.com/opencog/opencog/pull/1736/files#diff-12> (10)
>    - *M* opencog/python/blending/src/chooser/base_chooser.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-13> (38)
>    - *M* opencog/python/blending/src/chooser/choose_all.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-14> (35)
>    - *M* opencog/python/blending/src/chooser/choose_in_sti_range.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-15> (63)
>    - *M* opencog/python/blending/src/chooser/choose_null.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-16> (15)
>    - *M* opencog/python/blending/src/chooser/chooser_finder.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-17> (20)
>    - *M* opencog/python/blending/src/connector/README.md
>    <https://github.com/opencog/opencog/pull/1736/files#diff-18> (19)
>    - *M* opencog/python/blending/src/connector/base_connector.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-19> (46)
>    - *A*
>    opencog/python/blending/src/connector/connect_conflict_interaction_information.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-20> (497)
>    - *M* opencog/python/blending/src/connector/connect_conflict_random.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-21> (118)
>    - *M* opencog/python/blending/src/connector/connect_conflict_viable.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-22> (129)
>    - *M* opencog/python/blending/src/connector/connect_simple.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-23> (90)
>    - *M* opencog/python/blending/src/connector/connect_util.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-24> (311)
>    - *M* opencog/python/blending/src/connector/connector_finder.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-25> (26)
>    - *M* opencog/python/blending/src/connector/equal_link_key.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-26> (100)
>    - *M* opencog/python/blending/src/decider/README.md
>    <https://github.com/opencog/opencog/pull/1736/files#diff-27> (9)
>    - *M* opencog/python/blending/src/decider/base_decider.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-28> (37)
>    - *M* opencog/python/blending/src/decider/decide_best_sti.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-29> (63)
>    - *M* opencog/python/blending/src/decider/decide_null.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-30> (12)
>    - *M* opencog/python/blending/src/decider/decide_random.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-31> (27)
>    - *M* opencog/python/blending/src/decider/decider_finder.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-32> (20)
>    - *M* opencog/python/blending/src/maker/README.md
>    <https://github.com/opencog/opencog/pull/1736/files#diff-33> (6)
>    - *M* opencog/python/blending/src/maker/base_maker.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-34> (37)
>    - *M* opencog/python/blending/src/maker/make_simple.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-35> (33)
>    - *M* opencog/python/blending/src/maker/maker_finder.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-36> (20)
>    - *M* opencog/python/blending/util/README.md
>    <https://github.com/opencog/opencog/pull/1736/files#diff-37> (6)
>    - *M* opencog/python/blending/util/blending_config.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-38> (454)
>    - *M* opencog/python/blending/util/blending_error.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-39> (17)
>    - *M* opencog/python/blending/util/blending_util.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-40> (5)
>    - *M* opencog/python/blending/util/py_cog_execute.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-41> (36)
>    - *M* tests/python/blending_test/link_connector_test.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-42> (78)
>    - *M* tests/python/blending_test/test_conceptual_blending_base.py
>    <https://github.com/opencog/opencog/pull/1736/files#diff-43> (113)
>
> Patch Links:
>
>    - https://github.com/opencog/opencog/pull/1736.patch
>    - https://github.com/opencog/opencog/pull/1736.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/pull/1736>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by ngeiswei** [comment]
Cool. @kim135797531 you no longer need to include unit test outputs since ciclerci automatically produces it :-)

Assuming I'm the one in charge of merging it, the code seems to look good. I'm just gonna test it and merge.

**Comment by ngeiswei** [comment]
@kim135797531 The interaction information example works. However I had to add
```bash
export PYTHONPATH=$PYTHONPATH:/home/nilg/OpenCog/opencog-kim/opencog/python
```
You should at least specify that in `opencog/python/blending/README.md`.

Perhaps you should also update the CMake config file to install that the blending lib under`/usr/local/share/opencog/python/` (guys, is that a correct location?).

While you're at the README.md, please make it a bit more readable as well (more newlines and 80-col max, for us nerds that directly read the markdown source in the editor).

Thanks!

**Comment by kim135797531** [comment]
@ngeiswei I wrote a instruction about python path, and tried to keep 80-col max.

BTW, I think the location `/usr/local/share/opencog/python/` is a directory for atomspace's or opencog's cython binding library, and `$(source root)/opencog/python` is a directory for python file.

I'm not sure, but other modules in python directory are also not in `/usr/local/share/opencog/python`. Is the python source files are should be copied to install path?

**Comment by kim135797531** [comment]
The commit was amended to update the README.md to change about python path. Previous commit was kim135797531@c364f39f.

**Pull request merged**
