### PR TITLE
HebbianLinks updating wihout creating InverseHebbianLink  

### PR DESCRIPTION
**Pull request by misgeatgit**
This work is in an effort to address https://github.com/opencog/opencog/issues/1293

### CODE REVIEW

**Comment by linas** [comment]
Should @cosmoharrigan  be reviewing and merging instead of me?  Or maybe even @moikle ?

**Comment by williampma** [comment]
Is this breaking the HebbianUpdatingAgentUTest?

**Comment by misgeatgit** [comment]
Thanks @williampma the culprit  is https://github.com/misgeatgit/opencog/commit/55280717e7f59d36fce1fbadbe1300ad2284e72d. I believe what needs to be done is changing the test case as per our previous discussion that truth value updating should mean merging(applying a revision rule) instead of assigning a new truth value. @bgoertzel and @moikle  what is your opinion?

**Comment by moikle** [comment]
That would make sense to me. Also, the HebbianUpdatingAgentUTest code is still referencing InverseHebbian links which no longer exist?

—matt

**Comment by misgeatgit** [comment]
@moikle  the referencing won't cause a problem since the new implementation is in a separate class.

**Pull request merged**
