### PR TITLE
Added support for CORS to Rest API

### PR DESCRIPTION
**Pull request by inflector**
This should fix the problem George is having.

### CODE REVIEW

**Comment by AmeBel** [comment]
I am not getting restapi.Start in opencog shell. PYTHONPATH is set as described in http://wiki.opencog.org/w/Python. What am i missing?

**Comment by cosmoharrigan** [comment]
@AmeBel Does the REST API unit test pass on your machine? Do you have all the Python dependencies that it utilizes?

**Comment by AmeBel** [comment]
The Unit test doesn't run, i get.

```
opencog@193046552ef0:~/tests/python$ python test_restapi.py
Traceback (most recent call last):
  File "test_restapi.py", line 13, in <module>
    raise unittest.SkipTest("ImportError exception: make sure the required "
unittest.case.SkipTest: ImportError exception: make sure the required dependencies are installed.
```
are there any other dependencies other than those listed in https://github.com/opencog/opencog/blob/master/opencog/python/requirements.txt ?

**Comment by cosmoharrigan** [comment]
If you comment out 'try' and the entire 'except' clause, and just leave [this line](https://github.com/opencog/opencog/blob/6fad61aca3fb7af0ccfb01bf2ca98b69b5ec6699/tests/python/test_restapi.py#L10), then it should tell you what's missing.

**Comment by AmeBel** [comment]
ok it is a new dependency pip install -U flask-cors

**Pull request merged**
