### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by hedayat**
1.A race in AgentRunnerThread
2. add endlines to agents-start help message
3. GCC 5.3.1 compiler/functional fix
4. Refactoring some names to make code more clear and to better adhere to OpenCog coding standards
5. Add some documentation for Runner classes and their members

### CODE REVIEW

**Comment by pennachin** [comment]
@hedayat is this ready for merging?

**Comment by hedayat** [comment]
I am going to push some other changes (e.g. adding documents for 3 classes), but this PR can be merged safely now.

**Comment by pennachin** [comment]
Ok, let me know when you're done (and the branch is up to date) and I'll merge...

**Comment by hedayat** [comment]
Ready! Thank you.

**Pull request merged**
