### PR TITLE
Remove all files duplicated in opencog/learn

### PR DESCRIPTION
**Pull request by linas**
Per issue #3391 this splits out the language learning code into it's own github repo. That repo has already been created, as https://github.com/opencog/learn -- this removes teh duplicated files, so that they can be re-added as a git submodule.

### CODE REVIEW

**Comment by linas** [comment]
@akolonin this split affects your group. Let me know what you think.

**Comment by akolonin** [comment]
@glicerico @AmeBel @leungmanhin - if there are any conflicts with your changes?

**Comment by linas** [comment]
I'd like to merge this someday... any final remarks/issues? @glicerico @AmeBel @leungmanhin -

**Comment by AmeBel** [comment]
The codes are in sync, checked using `diff`. Cmake configuration needs tuning, I will make a pr in opencog/learn. So, it is fine by me if it is merged.

**Comment by leungmanhin** [comment]
I'm fine about this too

**Comment by glicerico** [comment]
I don't see any problems with this

**Pull request merged**
