### PR TITLE
Remove old pattern miner

### PR DESCRIPTION
**Pull request by ngeiswei**
The new pattern miner seems mature enough to replace it.

Tag of the old pattern miner: https://github.com/opencog/opencog/releases/tag/old-pattern-miner-11-Jun-2019

### CODE REVIEW

**Comment by ferrouswheel** [comment]
For people learning/catching up - like me ;-) - the new pattern miner is at https://github.com/opencog/opencog/tree/master/opencog/learning/miner

**Comment by ferrouswheel** [comment]
This causes undefined symbols in the AnaphoraUTest

```
16/38 Test #17: AnaphoraTest .....................***Failed    0.30 sec
Failure: ImportError (/usr/local/lib/python3/dist-packages/opencog/cogserver_type_constructors.so: undefined symbol: patternminer_types_init) ... ERROR

======================================================================
ERROR: Failure: ImportError (/usr/local/lib/python3/dist-packages/opencog/cogserver_type_constructors.so: undefined symbol: patternminer_types_init)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/ws/opencog/tests/nlp/anaphora/test_anaphora.py", line 8, in <module>
    from opencog.cogserver_type_constructors import types
ImportError: /usr/local/lib/python3/dist-packages/opencog/cogserver_type_constructors.so: undefined symbol: patternminer_types_init
```

**Comment by ferrouswheel** [comment]
Found the issue. I will make a PR soon...

**Comment by ferrouswheel** [comment]
@ngeiswei small tidy up in #3536

**Comment by ngeiswei** [comment]
Thanks, @ferrouswheel.

Information about the new pattern miner is also available on the wiki https://wiki.opencog.org/w/Pattern_miner

**Pull request merged**
