### PR TITLE
Reasoning: More Rule class update

### PR DESCRIPTION
**Pull request by williampma**
I am doing more mini push to avoid conflict.

- Switched to validate_bindlink (I noticed that function has an unneeded AtomSpace argument...)
- Added another functionality I am using, which is to make a Rule generate a standardize apart version of itself.
- Removed the disjunct_rules_ vector of pointers to make Rule object copy safe (it is better to have another class handle that).

I noticed two Handle to the same NodePtr cannot be compared if they are not added to an AtomSpace yet (because Handle == only compare uuid, which is not set yet), so ended up having to bypass validate_bindlink for the standardize apart version.

### CODE REVIEW

**Comment by misgeatgit** [comment]
I think you should add your name in the Author section.

**Comment by williampma** [comment]
What ordering are you referring to?

**Comment by misgeatgit** [comment]
I was referring to the ordering of public and private declarations in b7433391ec507776b6b7

**Comment by williampma** [comment]
Oh, just personal preference.  I am reading the header files like the "table of content" of a book, to allow me to quickly see what a class has available.  So I usually put public stuff at the top, since usually if I am looking at the header file, I do not care about the private stuff.

It is also why I am putting the doxygen stuff in the source rather than the header.

**Comment by misgeatgit** [comment]
Good to know.

**Pull request merged**
