### PR TITLE
Gradual nlp params

### PR DESCRIPTION
**Pull request by cuayacas7**
Continuing with the process of merging the two forks of the ULL pipeline...
The changes in this commit:
* I moved all the original scripts to a folder inside "run" directory named "old_scripts". They have been respectively modified so that it is still possible to run them from this folder (for backwards compatibility as required).
* I uploaded new scripts which I will summarize here:
    -- process-one.sh: replaces mst-one.sh and ss-one.sh files
    -- text-process.sh: replaces all the wiki-??-??.sh files
    -- run-multiple-terminals.sh: replaces the run-server-parse.sh and run-server-mst.sh files
    -- launch-cogserver.scm: replaces the mst-launch.scm and observe-launch.scm.
* Modified the utilities.scm file to receive an extra argument, the processing mode.
* Added the det-db-uri.sh script where the user can edit its own postgres username and password and set a default database name per language so it is not needed to pass as input to run-multiple-terminals.sh.
* Added the file params.txt where you can configure whether you want to print the mst-parses to an external txt-file.
* Both params.txt and process-one.sh have some things that have been commented out since have not been implemented yet in this commit, but will be used in the future.
* For further details on each of this files read the new README for the run directory (the old one has been kept inside old_scripts folder) .

### CODE REVIEW

**Comment by linas** [comment]
LOOK, i DON'T COME INTO YOUR KITCHEN, WHILE YOU ARE COOKING, STAND IN FRONT OF THE STOVE, AND START PUTTING SUGAR AND SALT INTO YOUR FOOD WHILE ITS COOKING.  WHY, EXACTLY, DO YOU THINK THAT IT IS SOCIALLY ACCEPTABLE TO DO THE SAME THING, BUT FOR CODE?

IF YOU WANT TO LEARN HOW TO COOK, ASK FOR HELP.  BUT DO NOT JUST COME IN AND START FUCKING OVER SOMETHING THAT ACTUALLY WORKS, AND WORKS QUITE WELL, AND REPLACE IT WITH TOOLS THAT DO NOT WORK, SCRIPTS THAT ARE BROKEN, AND README FILES THAT ARE INCORRECT. 

IN MOST PARTS OF THE WORLD, THIS IS CALLED "COMMON SENSE".  I DON'T MESS WITH YOUR MEALS, I DON'T COME TO YOUR HOUSE AND RE-ARRANGE YOUR FURNITURE.  SOURCE CODE AND COMPUTER PROGRAMS WORK THE SAME WAY.  DON'T DO ANYTHING ON-LINE THAT YOU WOULD NOT WANT DONE TO YOU IN REAL LIFE.

If you want to help, ask for how you can help. What you are currently doing is the opposite of help -- it is confrontational, provocative, aggressive and disrespectful.  Please stop behaving like this.

**Comment by bgoertzel** [comment]
LINAS -- I can think of no better response to your needlessly, unacceptably obnoxious message than to quote your last 2 sentences back at you... 

"What you are currently doing is the opposite of help -- it is confrontational, provocative, aggressive and disrespectful. Please stop behaving like this."

Claudia is really, truly doing her best to do WHAT YOU SEEMED TO BE ASKING HER TO DO.   She is a linguistics grad student not an experienced software engineer, and it's got to be OK to have linguistics grad students working on this research project -- and they really should be able to work on it without being bitched at in insane ways....

I ask you once more, PLEASE stop talking to people like this in the OpenCog context.  We are at a position now where we have a real opportunity to grow OpenCog in a massive way, and having our most productive developer treat young eager developers like shit, is the kind of thing that can make the whole project fail....

Regarding the Unsupervised Language Learning project, I am closer and closer to advocating that we indeed just split it into two different folders, language-learning-Linas, and language-learning-everyone-else ... and let there be replicated code in the two folders for now, understanding that they're likely to diverge anyway (e.g. I might like to replace the MST parser with a "maximum interaction information spanning tree" parser that uses interaction information estimates drawn from a neural net model, etc.).   Replicated code sucks but honestly,  not as badly as this negativity that you persist in smearing all over our project!!

I know you're genuinely annoyed and not just screaming at people for the lulz, but I also know you don't really want to damage the OpenCog project and community as much as you are doing !!

**Comment by linas** [comment]
Look, this is unacceptable behavior. It is outside of the norms of civil behavior.  You'd never walk into someones living room and leave a shit on their floor.  Only psychopaths do that in real life.  Psychopathic behavior on github is no different. To defend her obviously bad bad behavior is further indefensible.

This is not the first time.  There is a repeated pattern emerging here, of blatant and willful bad behavior.  Do not encourage her. Do not defend her. Her behavior is not cooperative; its an openly hostile act.

**Comment by bgoertzel** [comment]
On Thu, Jun 14, 2018 at 7:03 AM, Linas Vepštas <notifications@github.com>
wrote:

> Look, this is unacceptable behavior. It is outside of the norms of civil
> behavior. You'd never walk into someones living room and leave a shit on
> their floor. Only psychopaths do that in real life. Psychopathic behavior
> on github is no different. To defend her obviously bad bad behavior is
> further indefensible.
>
> This is not the first time. There is a repeated pattern emerging here, of
> blatant and willful bad behavior. Do not encourage her. Do not defend her.
> Her behavior is not cooperative; its an openly hostile act.
>


Dude, you're out of touch with reality here...

Claudia may be guilty here of poor judgment in some software-development or
codebase-management matters, but she just plain is not engaging in "openly
hostile" or "willfully bad" behavior....

You may indeed have a good sense for the software involved here, but your
erroneous perception of the human factors involved is reaching a point of
intolerability even for the more generous among us...

**Comment by ngeiswei** [comment]
No merging was enforced. It feels closer to a free speech analogy than a hijacked kitchen analogy (kitchens don't have `Merge` and `Revert` buttons).

**Pull request closed without merging**
