### PR TITLE
First moses pln synergy fc attempt

### PR DESCRIPTION
**Pull request by ngeiswei**
Can run the first 3 steps.

### CODE REVIEW

**Comment by ngeiswei** [comment]
retest this please

**Comment by ngeiswei** [comment]
@wenwei-dev @AmeBel jenkins seems frozen.

**Comment by ngeiswei** [comment]
@wenwei-dev @AmeBel jenkins seems frozen.

**Comment by AmeBel** [comment]
MOSESPLNSynergyUTest seems to be taking too long, let me test this pr on my machine

**Comment by ngeiswei** [comment]
Oh, I see. I've disabled it for that reason. I think "retest this please" should halt the current test and restart a new one.

**Comment by AmeBel** [comment]
retest this please

**Comment by AmeBel** [comment]
`retest this please` doesn't seem to reset a build, just cancelled it by going to http://61.92.69.43:8080/job/ci-opencog/148/console

**Comment by AmeBel** [comment]
stating jenkin's retest trigger phrase as part of any comment seems to trigger a retest.

**Pull request merged**
